/**
 * Default Google font family buckets (popular rail, display/script rail, wider offline fallback).
 *
 * Prefer wiring via `PageHubConfig.curatedGoogleFontFamilies` (React `PageHubProvider` or
 * `PageHub.init`). For tests or non-standard hosts, `setCuratedGoogleFontFamilies` in
 * `./googleFonts` is still available. Spread {@link DEFAULT_CURATED_GOOGLE_FONT_FAMILIES} to
 * tweak one list. Active lists are read via `getCuratedGoogleFontFamilies`.
 */
export type CuratedGoogleFontFamilies = {
  popular: readonly string[];
  funky: readonly string[];
  extended: readonly string[];
};

export const DEFAULT_CURATED_GOOGLE_FONT_FAMILIES = {
  popular: [
    "Roboto",
    "Open Sans",
    "Lato",
    "Montserrat",
    "Oswald",
    "Raleway",
    "PT Sans",
    "Merriweather",
    "Poppins",
    "Nunito",
    "Roboto Condensed",
    "Ubuntu",
    "Playfair Display",
    "Mukta",
    "Noto Sans",
    "Rubik",
    "Work Sans",
    "Inter",
    "Fira Sans",
    "Source Sans Pro",
    "Noto Serif",
    "Quicksand",
    "Karla",
    "Titillium Web",
    "Libre Baskerville",
    "Bitter",
    "Hind",
    "Cabin",
    "Dosis",
    "Crimson Text",
    "Inconsolata",
    "Oxygen",
    "Droid Sans",
    "Libre Franklin",
    "Josefin Sans",
    "Barlow",
    "EB Garamond",
    "PT Serif",
    "Abel",
    "Arimo",
    "Heebo",
    "DM Sans",
    "Mulish",
    "Manrope",
    "Nanum Gothic",
    "Archivo",
    "Exo 2",
    "Lora",
    "IBM Plex Sans",
    "Comfortaa",
  ],
  funky: [
    "Pacifico",
    "Lobster",
    "Righteous",
    "Permanent Marker",
    "Bebas Neue",
    "Abril Fatface",
    "Fredoka One",
    "Staatliches",
    "Russo One",
    "Orbitron",
    "Press Start 2P",
    "Indie Flower",
    "Architects Daughter",
    "Shadows Into Light",
    "Caveat",
    "Dancing Script",
    "Great Vibes",
    "Satisfy",
    "Tangerine",
    "Kaushan Script",
  ],
  extended: [
    "Crimson Pro",
    "Libre Baskerville",
    "Playfair Display",
    "Merriweather",
    "Lora",
    "PT Serif",
    "Vollkorn",
    "Cormorant",
    "Spectral",
    "Cardo",
    "Alegreya",
    "Noto Serif",
    "Source Serif Pro",
    "Tinos",
    "Gelasio",
    "Domine",
    "Arvo",
    "Bitter",
    "Neuton",
    "Old Standard TT",
    "Crimson Text",
    "Gentium Book Basic",
    "Coustard",
    "Alice",
    "Amiri",
    "Goudy Bookletter 1911",
    "Inter",
    "Roboto",
    "Open Sans",
    "Lato",
    "Montserrat",
    "Poppins",
    "Nunito",
    "Raleway",
    "Ubuntu",
    "Work Sans",
    "Rubik",
    "Source Sans Pro",
    "Mukta",
    "PT Sans",
    "Oswald",
    "Fira Sans",
    "Hind",
    "Cabin",
    "Karla",
    "Titillium Web",
    "Quicksand",
    "Oxygen",
    "Dosis",
    "Barlow",
    "Manrope",
    "DM Sans",
    "Mulish",
    "Heebo",
    "Exo 2",
    "IBM Plex Sans",
    "Comfortaa",
    "Abel",
    "Archivo",
    "Noto Sans",
    "Red Hat Display",
    "Jost",
    "Asap",
    "Catamaran",
    "Public Sans",
    "Space Grotesk",
    "Bebas Neue",
    "Anton",
    "Righteous",
    "Staatliches",
    "Monoton",
    "Abril Fatface",
    "Fredoka One",
    "Audiowide",
    "Bungee",
    "Yellowtail",
    "Alfa Slab One",
    "Secular One",
    "Black Ops One",
    "Sigmar One",
    "Bowlby One SC",
    "Poiret One",
    "Titan One",
    "Creepster",
    "Fugaz One",
    "Pacifico",
    "Lobster",
    "Dancing Script",
    "Great Vibes",
    "Satisfy",
    "Kaushan Script",
    "Tangerine",
    "Allura",
    "Cookie",
    "Sacramento",
    "Indie Flower",
    "Shadows Into Light",
    "Caveat",
    "Architects Daughter",
    "Patrick Hand",
    "Amatic SC",
    "Courgette",
    "Kalam",
    "Handlee",
    "Roboto Mono",
    "Source Code Pro",
    "JetBrains Mono",
    "Fira Code",
    "Inconsolata",
    "Space Mono",
    "IBM Plex Mono",
    "Courier Prime",
    "Anonymous Pro",
    "Overpass Mono",
    "Ubuntu Mono",
    "PT Mono",
    "Roboto Condensed",
    "Libre Franklin",
    "Josefin Sans",
    "Nanum Gothic",
    "PT Sans Narrow",
    "Varela Round",
    "Lexend",
    "Merriweather Sans",
    "Encode Sans",
    "Sora",
    "Outfit",
    "Plus Jakarta Sans",
    "Epilogue",
    "Urbanist",
    "Figtree",
    "Albert Sans",
    "Bricolage Grotesque",
  ],
} satisfies CuratedGoogleFontFamilies;

/** Stock preset; same reference as {@link DEFAULT_CURATED_GOOGLE_FONT_FAMILIES}. */
export const CURATED_GOOGLE_FONT_FAMILIES = DEFAULT_CURATED_GOOGLE_FONT_FAMILIES;
