// GENERATED by scripts/vendor-leaflet-public.mjs — do not edit.
// Files live at public/_ph/leaflet/1.9.4/ and are served from the app's own origin.
// Regenerate: pnpm gen:vendor-leaflet-public

/** Leaflet version whose files are vendored into the app's public dir. */
export const LEAFLET_VERSION = "1.9.4";

/**
 * Root-relative directory holding leaflet.js, leaflet.css and images/.
 * Relative on purpose: it resolves against whatever origin serves the page,
 * so CSP `'self'` covers it and no base URL has to be configured.
 */
export const LEAFLET_PUBLIC_PATH = "/_ph/leaflet/1.9.4/";
