/**
 * ARIA / accessibility property definitions.
 */
import type { PropertyDef } from "../propertyDefs";

export const ariaProperties: PropertyDef[] = [
  {
    id: "ariaLabel",
    label: "Label",
    section: "properties",
    keywords: ["aria", "label", "screen reader", "accessibility", "a11y"],
    input: { type: "text", placeholder: "Descriptive label for screen readers" },
    propType: "component",
    sortOrder: 100,
    inline: true,
  },
  {
    id: "ariaDescribedBy",
    label: "Described By",
    section: "properties",
    keywords: ["aria", "described", "by", "description", "a11y"],
    input: { type: "text", placeholder: "ID of element that describes this" },
    propType: "component",
    sortOrder: 110,
    inline: true,
  },
  {
    id: "ariaExpanded",
    label: "Expanded",
    section: "properties",
    keywords: ["aria", "expanded", "collapsed", "toggle", "a11y"],
    input: {
      type: "select",
      options: [
        { label: " ", value: "" },
        { label: "Expanded", value: "true" },
        { label: "Collapsed", value: "false" },
      ],
    },
    propType: "component",
    sortOrder: 120,
    inline: true,
  },
  {
    id: "ariaSelected",
    label: "Selected",
    section: "properties",
    keywords: ["aria", "selected", "active", "a11y"],
    input: {
      type: "select",
      options: [
        { label: " ", value: "" },
        { label: "Selected", value: "true" },
        { label: "Not Selected", value: "false" },
      ],
    },
    propType: "component",
    sortOrder: 130,
    inline: true,
  },
  {
    id: "role",
    label: "Role",
    section: "properties",
    keywords: ["aria", "role", "semantic", "button", "link", "navigation", "a11y"],
    input: {
      type: "select",
      options: [
        { label: " ", value: "" },
        { label: "Button", value: "button" },
        { label: "Link", value: "link" },
        { label: "Heading", value: "heading" },
        { label: "Image", value: "img" },
        { label: "Navigation", value: "navigation" },
        { label: "Main", value: "main" },
        { label: "Complementary", value: "complementary" },
        { label: "Content Info", value: "contentinfo" },
        { label: "Banner", value: "banner" },
        { label: "Search", value: "search" },
        { label: "Form", value: "form" },
        { label: "List", value: "list" },
        { label: "List Item", value: "listitem" },
        { label: "Menu Item", value: "menuitem" },
        { label: "Tab", value: "tab" },
        { label: "Tab Panel", value: "tabpanel" },
        { label: "Dialog", value: "dialog" },
        { label: "Alert", value: "alert" },
        { label: "Status", value: "status" },
        { label: "Progress Bar", value: "progressbar" },
        { label: "Slider", value: "slider" },
        { label: "Checkbox", value: "checkbox" },
        { label: "Radio", value: "radio" },
        { label: "Textbox", value: "textbox" },
        { label: "Combobox", value: "combobox" },
        { label: "Listbox", value: "listbox" },
        { label: "Tree", value: "tree" },
        { label: "Grid", value: "grid" },
        { label: "Table", value: "table" },
        { label: "Presentation", value: "presentation" },
      ],
    },
    propType: "component",
    sortOrder: 140,
    inline: true,
  },
  {
    id: "tabIndex",
    label: "Tab Index",
    section: "properties",
    keywords: ["tab", "index", "focus", "keyboard", "order", "a11y"],
    input: {
      type: "select",
      options: [
        { label: "Default", value: "" },
        { label: "Focusable (0)", value: "0" },
        { label: "Not Focusable (-1)", value: "-1" },
        { label: "First Priority (1)", value: "1" },
        { label: "Second Priority (2)", value: "2" },
        { label: "Third Priority (3)", value: "3" },
      ],
    },
    propType: "component",
    sortOrder: 150,
    inline: true,
  },
  {
    id: "ariaHidden",
    label: "Hidden",
    section: "properties",
    keywords: ["aria", "hidden", "screen reader", "invisible", "a11y"],
    input: {
      type: "select",
      options: [
        { label: " ", value: "" },
        { label: "Hidden from screen readers", value: "true" },
        { label: "Visible to screen readers", value: "false" },
      ],
    },
    propType: "component",
    sortOrder: 160,
    inline: true,
  },
  {
    id: "ariaLive",
    label: "Live",
    section: "properties",
    keywords: ["aria", "live", "polite", "assertive", "announce", "a11y"],
    input: {
      type: "select",
      options: [
        { label: " ", value: "" },
        { label: "Off", value: "off" },
        { label: "Polite", value: "polite" },
        { label: "Assertive", value: "assertive" },
      ],
    },
    propType: "component",
    sortOrder: 170,
    inline: true,
  },
];
