/**
 * Built-in section definitions.
 *
 * These define the accordion sections that appear in each tab.
 * Properties reference these by section ID.
 */
import React from "react";
import {
  TbArrowsExchange,
  TbArrowsMaximize,
  TbBolt,
  TbCode,
  TbDatabase,
  TbEyeSearch,
  TbHandMove,
  TbLayout,
  TbLock,
  TbPhotoFilled,
  TbPointer,
  TbSettings2,
  TbSparkles,
  TbStack2,
  TbTypography,
  TbWand,
} from "react-icons/tb";
import type { SectionDef } from "../propertyDefs";

export const BUILT_IN_SECTIONS: SectionDef[] = [
  // ─── Component tab ─────────────────────────────────────────────────
  {
    id: "component",
    title: "Component",
    tab: "component",
    keywords: ["content", "settings", "props"],
    sortOrder: 0,
    defaultOpen: false,
    help: "Content and settings specific to this component.",
  },
  {
    id: "data-source",
    title: "Data source",
    tab: "component",
    icon: React.createElement(TbDatabase),
    keywords: [
      "data",
      "source",
      "stripe",
      "connector",
      "products",
      "repeater",
      "search",
      "category",
    ],
    sortOrder: 5,
    defaultOpen: false,
    help: "Where this node's repeater data comes from — connector collections, filters, and URL refetch options.",
  },
  {
    id: "modifiers",
    title: "Modifiers",
    tab: "layout",
    icon: React.createElement(TbStack2),
    keywords: ["modifier", "pattern", "variant", "style", "class", "toggle"],
    hideKey: "modifiers",
    sortOrder: 10,
    help: "Toggle pre-built style variants and patterns.",
  },
  {
    id: "preset-items",
    title: "Items",
    tab: "layout",
    icon: React.createElement(TbLayout),
    keywords: ["items", "add", "child", "preset", "list"],
    sortOrder: 5,
    help: "Add or remove children for this preset (Accordion items, tabs, etc.).",
    defaultOpen: true,
  },

  // ─── Layout tab ────────────────────────────────────────────────────
  {
    id: "alignment",
    title: "Layout",
    tab: "layout",
    icon: React.createElement(TbLayout),
    keywords: ["layout", "preset", "gap", "gutter", "alignment", "align", "justify", "direction", "flex", "grid", "row", "column", "block"],
    hideKey: "alignment",
    sortOrder: 15,
    help: "Layout preset, direction, gap, and child alignment.",
  },
  {
    id: "size",
    title: "Size",
    tab: "layout",
    icon: React.createElement(TbArrowsMaximize),
    keywords: ["width", "height", "min", "max", "aspect"],
    hideKey: "size",
    sortOrder: 20,
    help: "Width, height, min/max size, and aspect ratio.",
  },
  // ─── Design tab ────────────────────────────────────────────────────
  {
    id: "typography",
    title: "Text",
    tab: "design",
    icon: React.createElement(TbTypography),
    keywords: [
      "font",
      "text",
      "size",
      "weight",
      "line-height",
      "letter-spacing",
      "color",
      "align",
      "family",
    ],
    hideKey: "font",
    sortOrder: 10,
    help: "Font family, size, weight, color, and text alignment.",
  },
  {
    id: "background",
    title: "Background",
    tab: "design",
    icon: React.createElement(TbPhotoFilled),
    keywords: ["color", "image", "gradient", "pattern", "fill", "bg"],
    hideKey: "background",
    sortOrder: 20,
    help: "Background color, image, gradient, and pattern.",
  },
  {
    // Hosted exclusively in the cog popover off the Background image chip
    // (see `BackgroundImageSettingsBody` → `<PropertySection sectionId="image-settings" />`).
    // `searchOnly: true` keeps it out of the main inspector tab body — the
    // section still resolves via getSectionDef / getProperties so the popover
    // can render it; tab views call `getSectionDefs({ tab }).filter(s => !s.searchOnly)`.
    id: "image-settings",
    title: "Image Settings",
    tab: "design",
    icon: React.createElement(TbPhotoFilled),
    keywords: ["loading", "lazy", "priority", "repeat", "size", "origin", "position", "attachment"],
    sortOrder: 25,
    searchOnly: true,
    help: "Loading + tile/repeat/position controls for a background image.",
  },
  {
    id: "styles",
    title: "Styles",
    tab: "design",
    icon: React.createElement(TbSparkles),
    keywords: [
      "opacity",
      "shadow",
      "border",
      "radius",
      "rounded",
      "corners",
      "ring",
      "outline",
      "filter",
      "blur",
      "backdrop",
      "divide",
      "visibility",
      "overflow",
      "cursor",
      "z-index",
      "pointer",
      "user-select",
      "fade",
      "transparent",
      "stroke",
      "solid",
      "dashed",
      "dotted",
    ],
    sortOrder: 30,
    help: "Opacity, surface, border, ring/outline, filter, behavior — anything that paints or hides.",
  },
  // The "Transforms" section was merged into the unified Effects builder.
  {
    id: "advanced-settings",
    title: "Advanced Settings",
    tab: "design",
    keywords: [],
    sortOrder: 50,
  },

  // ─── Interactions tab ──────────────────────────────────────────────
  {
    id: "action",
    title: "Action",
    tab: "component",
    icon: React.createElement(TbPointer),
    keywords: [
      "action",
      "click",
      "link",
      "scroll",
      "modal",
      "email",
      "phone",
      "url",
      "download",
      "cart",
    ],
    hideKey: "hoverClick",
    sortOrder: 10,
    help: "What happens on click — link, scroll, modal, cart, and more.",
  },
  {
    id: "hover",
    title: "Hover",
    tab: "interactions",
    icon: React.createElement(TbHandMove),
    keywords: ["hover", "mouse", "over", "color", "scale", "opacity", "transform", "shadow"],
    hideKey: "hoverClick",
    sortOrder: 15,
    help: "Styling that applies while the cursor is over this element.",
  },
  {
    id: "conditions",
    title: "Conditions",
    tab: "interactions",
    icon: React.createElement(TbEyeSearch),
    keywords: ["condition", "visibility", "show", "hide", "url", "form"],
    sortOrder: 20,
    help: "Show or hide this element based on URL, auth, or form state.",
  },
  {
    id: "stateBindings",
    title: "State",
    tab: "interactions",
    icon: React.createElement(TbBolt),
    keywords: [
      "state",
      "active",
      "open",
      "selected",
      "tab",
      "modifier",
      "binding",
      "condition",
    ],
    sortOrder: 22,
    help: "Bind modifiers to runtime state — e.g. apply 'active' classes when a paired panel is shown.",
  },
  // Animation, "Tailwind effects", Scroll Effect — collapsed into one
  // unified Effects section (Design tab) backed by effects-builder/. See
  // registry/properties/effects.ts.
  {
    id: "effects",
    title: "Effects",
    tab: "design",
    icon: React.createElement(TbBolt),
    keywords: [
      "effect",
      "effects",
      "animation",
      "animate",
      "motion",
      "entrance",
      "transition",
      "duration",
      "ease",
      "delay",
      "transform",
      "scale",
      "rotate",
      "translate",
      "skew",
      "filter",
      "blur",
      "brightness",
      "saturate",
      "backdrop",
      "frosted",
      "glass",
      "scroll",
      "horizontal",
      "timeline",
      "pin",
      "gsap",
      "parallax",
      "fade",
      "slide",
      "spring",
      "bounce",
    ],
    hideKey: "effectsClass",
    sortOrder: 38,
    help: "Animation, scroll, transition, transform, filter, and backdrop effects.",
  },
  // ─── Advanced tab ──────────────────────────────────────────────────
  {
    id: "properties",
    title: "Attributes",
    tab: "advanced",
    icon: React.createElement(TbSettings2),
    keywords: [
      "id",
      "element",
      "tag",
      "html",
      "data",
      "attribute",
      "accessibility",
      "aria",
      "role",
      "label",
      "tab-index",
      "screen-reader",
      "a11y",
    ],
    hideKey: "accessibility",
    sortOrder: 10,
    help: "HTML tag, ID, data attributes, and ARIA / accessibility.",
  },
  {
    id: "custom-css",
    title: "Classes",
    tab: "advanced",
    icon: React.createElement(TbCode),
    keywords: ["css", "class", "className", "tailwind", "custom", "code", "classes"],
    sortOrder: 25,
    help: "Add or edit Tailwind and custom class names.",
  },
  {
    id: "ai-context",
    title: "AI Context",
    tab: "advanced",
    icon: React.createElement(TbWand),
    keywords: ["ai", "context", "description", "block", "notes", "tags", "assistant"],
    sortOrder: 35,
    help: "Optional notes/tags so AI understands this component.",
  },
  {
    id: "import-export",
    title: "Import / Export",
    tab: "advanced",
    icon: React.createElement(TbArrowsExchange),
    keywords: ["json", "copy", "paste", "import", "export", "code"],
    hideKey: "importExport",
    sortOrder: 40,
    help: "Copy this node as JSON or paste JSON to replace it.",
  },
  {
    id: "permissions",
    title: "Permissions",
    tab: "advanced",
    icon: React.createElement(TbLock),
    keywords: ["permission", "lock", "drag", "delete", "edit", "move", "protect", "restrict"],
    sortOrder: 200,
    help: "Lock down what can be done with this node.",
  },
];
