/**
 * Built-in section definitions.
 *
 * These define the accordion sections that appear in each tab.
 * Properties reference these by section ID.
 */
import React from "react";
import {
  TbArrowsExchange,
  TbArrowsMaximize,
  TbBolt,
  TbCode,
  TbDatabase,
  TbEyeSearch,
  TbHandMove,
  TbLayout,
  TbLock,
  TbPhotoFilled,
  TbPointer,
  TbSettings2,
  TbSparkles,
  TbStack2,
  TbTypography,
  TbWand,
} from "react-icons/tb";
import type { SectionDef } from "../propertyDefs";

export const BUILT_IN_SECTIONS: SectionDef[] = [
  // ─── Component tab ─────────────────────────────────────────────────
  {
    id: "component",
    title: "Component",
    tab: "component",
    keywords: ["content", "settings", "props"],
    sortOrder: 0,
    defaultOpen: false,
    help: "Settings that only this kind of thing has.",
  },
  {
    id: "data-source",
    title: "Data source",
    tab: "component",
    icon: React.createElement(TbDatabase),
    keywords: [
      "data",
      "source",
      "stripe",
      "connector",
      "products",
      "repeater",
      "search",
      "category",
    ],
    sortOrder: 5,
    defaultOpen: false,
    help: "Where the list pulls its data from.",
  },
  {
    id: "modifiers",
    title: "Modifiers",
    tab: "layout",
    icon: React.createElement(TbStack2),
    keywords: ["modifier", "pattern", "variant", "style", "class", "toggle"],
    hideKey: "modifiers",
    sortOrder: 10,
    help: "One-click style presets you can stack on top.",
  },
  {
    id: "preset-items",
    title: "Items",
    tab: "layout",
    icon: React.createElement(TbLayout),
    keywords: ["items", "add", "child", "preset", "list"],
    sortOrder: 5,
    help: "Add or remove the items inside this group.",
    defaultOpen: true,
  },

  // ─── Layout tab ────────────────────────────────────────────────────
  {
    id: "alignment",
    title: "Layout",
    tab: "layout",
    icon: React.createElement(TbLayout),
    keywords: [
      "layout",
      "preset",
      "gap",
      "gutter",
      "alignment",
      "align",
      "justify",
      "direction",
      "flex",
      "grid",
      "row",
      "column",
      "block",
    ],
    hideKey: "alignment",
    sortOrder: 15,
    help: "Where stuff sits — rows, columns, gaps, alignment.",
  },
  {
    id: "size",
    title: "Size",
    tab: "layout",
    icon: React.createElement(TbArrowsMaximize),
    keywords: ["width", "height", "min", "max", "aspect"],
    hideKey: "size",
    sortOrder: 20,
    help: "How wide, tall, and big this thing is.",
  },
  // ─── Design tab ────────────────────────────────────────────────────
  {
    id: "typography",
    title: "Text",
    tab: "design",
    icon: React.createElement(TbTypography),
    keywords: [
      "font",
      "text",
      "size",
      "weight",
      "line-height",
      "letter-spacing",
      "color",
      "align",
      "family",
    ],
    hideKey: "font",
    sortOrder: 10,
    help: "Font, size, weight, colour, alignment for the words.",
  },
  {
    id: "background",
    title: "Background",
    tab: "design",
    icon: React.createElement(TbPhotoFilled),
    keywords: ["color", "image", "gradient", "pattern", "fill", "bg"],
    hideKey: "background",
    sortOrder: 20,
    help: "What sits behind — colour, image, gradient, pattern.",
  },
  {
    // Hosted exclusively in the cog popover off the Background image chip
    // (see `BackgroundImageSettingsBody` → `<PropertySection sectionId="image-settings" />`).
    // `searchOnly: true` keeps it out of the main inspector tab body — the
    // section still resolves via getSectionDef / getProperties so the popover
    // can render it; tab views call `getSectionDefs({ tab }).filter(s => !s.searchOnly)`.
    id: "image-settings",
    title: "Image Settings",
    tab: "design",
    icon: React.createElement(TbPhotoFilled),
    keywords: ["loading", "lazy", "priority", "repeat", "size", "origin", "position", "attachment"],
    sortOrder: 25,
    searchOnly: true,
    help: "How the background image loads, repeats, and positions.",
  },
  {
    id: "hover",
    title: "Hover",
    tab: "design",
    icon: React.createElement(TbHandMove),
    keywords: ["hover", "mouse", "over", "color", "scale", "opacity", "transform", "shadow"],
    hideKey: "hoverClick",
    sortOrder: 32,
    help: "How it looks when the mouse is over it.",
  },
  {
    id: "styles",
    title: "Styles",
    tab: "design",
    icon: React.createElement(TbSparkles),
    keywords: [
      "opacity",
      "shadow",
      "border",
      "radius",
      "rounded",
      "corners",
      "ring",
      "outline",
      "filter",
      "blur",
      "backdrop",
      "divide",
      "visibility",
      "overflow",
      "cursor",
      "z-index",
      "pointer",
      "user-select",
      "fade",
      "transparent",
      "stroke",
      "solid",
      "dashed",
      "dotted",
    ],
    sortOrder: 30,
    help: "Edges, shadow, opacity, corners, blur — the paint job.",
  },
  // The "Transforms" section was merged into the unified Effects builder.
  {
    id: "advanced-settings",
    title: "Advanced Settings",
    tab: "design",
    keywords: [],
    sortOrder: 50,
  },

  // ─── Interactions tab ──────────────────────────────────────────────
  // "What does this node DO" — typed actions, raw JS handlers, visibility
  // conditions, runtime state bindings. Pure styling stays on the Design tab
  // (Hover lives there now — it's a style variant, not behavior).
  {
    id: "action",
    title: "Action",
    tab: "interactions",
    icon: React.createElement(TbPointer),
    keywords: [
      "action",
      "click",
      "link",
      "scroll",
      "modal",
      "email",
      "phone",
      "url",
      "download",
      "cart",
    ],
    hideKey: "hoverClick",
    sortOrder: 10,
    help: "What happens when someone clicks it.",
  },
  {
    id: "handlers",
    title: "Handlers",
    tab: "interactions",
    icon: React.createElement(TbCode),
    keywords: [
      "handler",
      "event",
      "javascript",
      "js",
      "code",
      "click",
      "hover",
      "mouseenter",
      "mouseleave",
      "focus",
      "blur",
      "keydown",
      "keyup",
    ],
    hideKey: "hoverClick",
    sortOrder: 15,
    help: "Run your own JavaScript when an event fires.",
  },
  {
    id: "conditions",
    title: "Conditions",
    tab: "interactions",
    icon: React.createElement(TbEyeSearch),
    keywords: ["condition", "visibility", "show", "hide", "url", "form"],
    sortOrder: 20,
    help: "Rules that show or hide this in real time.",
  },
  {
    id: "stateBindings",
    title: "State",
    tab: "interactions",
    icon: React.createElement(TbBolt),
    keywords: ["state", "active", "open", "selected", "tab", "modifier", "binding", "condition"],
    sortOrder: 22,
    help: "React to runtime state — e.g. 'active' when a panel opens.",
  },
  // Animation, "Tailwind effects", Scroll Effect — collapsed into one
  // unified Effects section (Design tab) backed by effects-builder/. See
  // registry/properties/effects.ts.
  {
    id: "effects",
    title: "Effects",
    tab: "design",
    icon: React.createElement(TbBolt),
    keywords: [
      "effect",
      "effects",
      "animation",
      "animate",
      "motion",
      "entrance",
      "transition",
      "duration",
      "ease",
      "delay",
      "transform",
      "scale",
      "rotate",
      "translate",
      "skew",
      "filter",
      "blur",
      "brightness",
      "saturate",
      "backdrop",
      "frosted",
      "glass",
      "scroll",
      "horizontal",
      "timeline",
      "pin",
      "gsap",
      "parallax",
      "fade",
      "slide",
      "spring",
      "bounce",
    ],
    hideKey: "effectsClass",
    sortOrder: 38,
    help: "Movement and motion — animations, transitions, parallax.",
  },
  // ─── Advanced tab ──────────────────────────────────────────────────
  {
    id: "properties",
    title: "Attributes",
    tab: "advanced",
    icon: React.createElement(TbSettings2),
    keywords: [
      "id",
      "element",
      "tag",
      "html",
      "data",
      "attribute",
      "accessibility",
      "aria",
      "role",
      "label",
      "tab-index",
      "screen-reader",
      "a11y",
    ],
    hideKey: "accessibility",
    sortOrder: 10,
    help: "HTML tag, IDs, data-attrs, accessibility.",
  },
  {
    id: "custom-css",
    title: "Classes",
    tab: "advanced",
    icon: React.createElement(TbCode),
    keywords: ["css", "class", "className", "tailwind", "custom", "code", "classes"],
    sortOrder: 25,
    help: "Raw Tailwind and custom class names.",
  },
  {
    id: "ai-context",
    title: "AI Context",
    tab: "advanced",
    icon: React.createElement(TbWand),
    keywords: ["ai", "context", "description", "block", "notes", "tags", "assistant"],
    sortOrder: 35,
    help: "Notes that help AI understand this thing.",
  },
  {
    id: "import-export",
    title: "Import / Export",
    tab: "advanced",
    icon: React.createElement(TbArrowsExchange),
    keywords: ["json", "copy", "paste", "import", "export", "code"],
    hideKey: "importExport",
    sortOrder: 40,
    help: "Copy this as JSON or paste JSON to replace it.",
  },
  {
    id: "permissions",
    title: "Permissions",
    tab: "advanced",
    icon: React.createElement(TbLock),
    keywords: ["permission", "lock", "drag", "delete", "edit", "move", "protect", "restrict"],
    sortOrder: 200,
    help: "Lock down what can be done with this.",
  },
];
