/**
 * Built-in section definitions.
 *
 * These define the accordion sections that appear in each tab.
 * Properties reference these by section ID.
 */
import React from "react";
import {
  TbAccessible,
  TbAdjustments,
  TbArrowsExchange,
  TbArrowsHorizontal,
  TbArrowsMaximize,
  TbBolt,
  TbBrandTailwind,
  TbChevronsDown,
  TbCode,
  TbDatabase,
  TbEyeSearch,
  TbHandMove,
  TbLayout,
  TbLayoutAlignCenter,
  TbLock,
  TbPointer,
  TbSettings2,
  TbSparkles,
  TbStack2,
  TbTypography,
  TbWand,
} from "react-icons/tb";
import { PiImageFill } from "react-icons/pi";
import type { SectionDef } from "../propertyDefs";

export const BUILT_IN_SECTIONS: SectionDef[] = [
  // ─── Component tab ─────────────────────────────────────────────────
  {
    id: "component",
    title: "Component",
    tab: "component",
    keywords: ["content", "settings", "props"],
    sortOrder: 0,
    defaultOpen: true,
    help: "Content and settings specific to this component.",
  },
  {
    id: "data-source",
    title: "Data source",
    tab: "component",
    icon: React.createElement(TbDatabase),
    keywords: [
      "data",
      "source",
      "stripe",
      "connector",
      "products",
      "repeater",
      "search",
      "category",
    ],
    sortOrder: 5,
    defaultOpen: true,
    help: "Where this node's repeater data comes from — connector collections, filters, and URL refetch options.",
  },
  {
    id: "modifiers",
    title: "Modifiers",
    tab: "advanced",
    icon: React.createElement(TbStack2),
    keywords: ["modifier", "pattern", "variant", "style", "class", "toggle"],
    hideKey: "modifiers",
    sortOrder: 24,
    help: "Toggle pre-built style variants and patterns.",
  },

  // ─── Layout tab ────────────────────────────────────────────────────
  {
    id: "alignment",
    title: "Layout",
    tab: "layout",
    icon: React.createElement(TbLayout),
    keywords: ["layout", "preset", "gap", "gutter", "alignment", "align", "justify", "direction", "flex", "grid", "row", "column", "block"],
    sortOrder: 15,
    help: "Layout preset, direction, gap, and child alignment.",
  },
  {
    id: "size",
    title: "Size",
    tab: "layout",
    icon: React.createElement(TbArrowsMaximize),
    keywords: ["width", "height", "min", "max", "aspect"],
    sortOrder: 20,
    help: "Width, height, min/max size, and aspect ratio.",
  },
  // ─── Design tab ────────────────────────────────────────────────────
  {
    id: "typography",
    title: "Typography",
    tab: "design",
    icon: React.createElement(TbTypography),
    keywords: [
      "font",
      "text",
      "size",
      "weight",
      "line-height",
      "letter-spacing",
      "color",
      "align",
      "family",
    ],
    hideKey: "font",
    sortOrder: 10,
    help: "Font family, size, weight, color, and text alignment.",
  },
  {
    id: "background",
    title: "Background",
    tab: "design",
    icon: React.createElement(PiImageFill),
    keywords: ["color", "image", "gradient", "pattern", "fill", "bg"],
    hideKey: "background",
    sortOrder: 20,
    help: "Background color, image, gradient, and pattern.",
  },
  {
    id: "styles",
    title: "Styles",
    tab: "design",
    icon: React.createElement(TbSparkles),
    keywords: [
      "opacity",
      "shadow",
      "border",
      "radius",
      "rounded",
      "corners",
      "ring",
      "outline",
      "filter",
      "blur",
      "backdrop",
      "divide",
      "visibility",
      "overflow",
      "cursor",
      "z-index",
      "pointer",
      "user-select",
      "fade",
      "transparent",
      "stroke",
      "solid",
      "dashed",
      "dotted",
    ],
    sortOrder: 30,
    help: "Opacity, surface, border, ring/outline, filter, behavior — anything that paints or hides.",
  },
  {
    id: "advanced-settings",
    title: "Advanced Settings",
    tab: "design",
    keywords: [],
    sortOrder: 50,
  },

  // ─── Interactions tab ──────────────────────────────────────────────
  {
    id: "action",
    title: "Action",
    tab: "component",
    icon: React.createElement(TbPointer),
    keywords: [
      "action",
      "click",
      "link",
      "scroll",
      "modal",
      "email",
      "phone",
      "url",
      "download",
      "cart",
    ],
    hideKey: "hoverClick",
    sortOrder: 10,
    help: "What happens on click — link, scroll, modal, cart, and more.",
  },
  {
    id: "hover",
    title: "Hover",
    tab: "interactions",
    icon: React.createElement(TbHandMove),
    keywords: ["hover", "mouse", "over", "color", "scale", "opacity", "transform", "shadow"],
    hideKey: "hoverClick",
    sortOrder: 15,
    help: "Styling that applies while the cursor is over this element.",
  },
  {
    id: "conditions",
    title: "Conditions",
    tab: "interactions",
    icon: React.createElement(TbEyeSearch),
    keywords: ["condition", "visibility", "show", "hide", "url", "form"],
    sortOrder: 20,
    help: "Show or hide this element based on URL, auth, or form state.",
  },
  {
    id: "animations",
    title: "Animation",
    tab: "interactions",
    icon: React.createElement(TbBolt),
    keywords: ["animate", "motion", "entrance", "scroll", "transition", "framer"],
    hideKey: "animations",
    sortOrder: 30,
    help: "Entrance and scroll-triggered motion.",
  },
  {
    id: "effects",
    title: "Tailwind effects",
    tab: "interactions",
    icon: React.createElement(TbBrandTailwind),
    keywords: [
      "transition",
      "transform",
      "filter",
      "backdrop",
      "blur",
      "scale",
      "rotate",
      "scroll",
      "timeline",
      "horizontal",
      "pin",
    ],
    hideKey: "effectsClass",
    sortOrder: 40,
    help: "Transform, filter, backdrop, and animation utilities.",
  },
  {
    id: "scroll-effect",
    title: "Scroll Effect",
    tab: "interactions",
    icon: React.createElement(TbChevronsDown),
    keywords: ["scroll", "horizontal", "timeline", "pin", "gsap", "section"],
    sortOrder: 45,
    help: "Pin-driven and horizontal scroll effects for section containers.",
  },
  {
    id: "overflow-scroll",
    title: "Overflow",
    tab: "interactions",
    icon: React.createElement(TbArrowsHorizontal),
    keywords: ["overflow", "scroll", "drag", "scrollbar", "horizontal", "carousel", "strip"],
    sortOrder: 46,
    help: "CSS overflow: drag-to-scroll and auto-hide scrollbar for horizontal rows (not GSAP scroll effects).",
  },

  // ─── Advanced tab ──────────────────────────────────────────────────
  {
    id: "properties",
    title: "Properties",
    tab: "advanced",
    icon: React.createElement(TbSettings2),
    keywords: ["id", "element", "tag", "html", "data", "attribute"],
    sortOrder: 10,
    help: "HTML tag, ID, and data attributes.",
  },
  {
    id: "aria",
    title: "ARIA",
    tab: "advanced",
    icon: React.createElement(TbAccessible),
    keywords: ["accessibility", "aria", "role", "label", "tab-index", "screen-reader"],
    hideKey: "accessibility",
    sortOrder: 20,
    help: "Accessibility attributes for screen readers and assistive tech.",
  },
  {
    id: "display",
    title: "Display",
    tab: "advanced",
    icon: React.createElement(TbAdjustments),
    keywords: ["visibility", "pointer", "cursor", "classname", "css"],
    sortOrder: 30,
    help: "Visibility, cursor, page breaks, and other CSS display options.",
  },
  {
    id: "custom-css",
    title: "Classes",
    tab: "advanced",
    icon: React.createElement(TbCode),
    keywords: ["css", "class", "className", "tailwind", "custom", "code", "classes"],
    sortOrder: 25,
    help: "Add or edit Tailwind and custom class names.",
  },
  {
    id: "ai-context",
    title: "AI context",
    tab: "advanced",
    icon: React.createElement(TbWand),
    keywords: ["ai", "context", "description", "block", "notes", "tags", "assistant"],
    sortOrder: 35,
    help: "Optional notes/tags so AI understands this component.",
  },
  {
    id: "import-export",
    title: "Import / Export",
    tab: "advanced",
    icon: React.createElement(TbArrowsExchange),
    keywords: ["json", "copy", "paste", "import", "export", "code"],
    hideKey: "importExport",
    sortOrder: 40,
    help: "Copy this node as JSON or paste JSON to replace it.",
  },
  {
    id: "permissions",
    title: "Permissions",
    tab: "advanced",
    icon: React.createElement(TbLock),
    keywords: ["permission", "lock", "drag", "delete", "edit", "move", "protect", "restrict"],
    sortOrder: 200,
    help: "Lock down what can be done with this node.",
  },
];
