/**
 * Typography property definitions — pure data, no JSX, no imports of inputs.
 * Custom inputs are referenced by string key into the customInputs registry.
 */
import React from "react";
import {
  TbBold,
  TbItalic,
  TbLineHeight,
  TbStrikethrough,
  TbTextWrap,
  TbUnderline,
} from "react-icons/tb";
import type { PropertyDef } from "../propertyDefs";

export const typographyProperties: PropertyDef[] = [
  {
    id: "typographyPreset",
    label: "Styles",
    section: "typography",
    keywords: ["styles", "preset", "typography", "heading", "body", "accent"],
    input: { type: "custom", component: "TypographyPresetInput" },
    pinned: true,
    sortOrder: -10,
    inline: true,
  },
  {
    id: "textAlign",
    label: "Text Align",
    section: "typography",
    keywords: ["align", "left", "center", "right", "justify", "start", "end"],
    input: { type: "tailwind-radio", tailwindKey: "textAlign", cols: true },
    sortOrder: 0,
  },
  {
    id: "fontFamily",
    label: "Family",
    section: "typography",
    keywords: ["font", "family", "typeface", "google", "heading", "body", "accent"],
    input: { type: "custom", component: "FontFamilyInput" },
    sortOrder: 10,
  },
  {
    id: "fontSize",
    label: "Size",
    section: "typography",
    keywords: ["size", "text", "large", "small", "xl", "2xl", "3xl"],
    input: {
      type: "tailwind-select",
      tailwindKey: "fontSize",
      showVarSelector: true,
      varSelectorPrefix: "text",
    },
    sortOrder: 20,
  },
  {
    id: "fontWeight",
    label: "Weight",
    section: "typography",
    keywords: ["weight", "bold", "light", "semibold", "thin", "medium", "heavy"],
    input: {
      type: "tailwind-select",
      tailwindKey: "fontWeight",
      showVarSelector: true,
      varSelectorPrefix: "font",
    },
    sortOrder: 30,
  },
  {
    id: "textColor",
    label: "Color",
    section: "typography",
    keywords: ["color", "text", "foreground", "font color"],
    input: { type: "color", prefix: "text" },
    hideKey: "textColor",
    sortOrder: 40,
    inline: true,
  },

  // ─── Spacing (bundle: line-height + tracking + indent) ──────────
  {
    id: "spacing",
    label: "Spacing",
    section: "typography",
    keywords: [
      "spacing",
      "line",
      "height",
      "leading",
      "tracking",
      "letter",
      "kerning",
      "indent",
      "paragraph",
    ],
    sortOrder: 100,
    input: {
      type: "bundle",
      icon: React.createElement(TbLineHeight, { className: "size-3.5" }),
      properties: [
        {
          id: "lineHeight",
          label: "Line Height",
          section: "typography",
          keywords: ["line", "height", "leading", "spacing", "vertical"],
          input: { type: "tailwind-select", tailwindKey: "lineHeight" },
          inline: true,
        },
        {
          id: "tracking",
          label: "Tracking",
          section: "typography",
          keywords: ["tracking", "letter", "spacing", "kerning"],
          input: { type: "tailwind-select", tailwindKey: "tracking" },
          inline: true,
        },
        {
          id: "indent",
          label: "Indent",
          section: "typography",
          keywords: ["indent", "paragraph", "first line"],
          input: { type: "tailwind-select", tailwindKey: "indent" },
          inline: true,
        },
      ],
    },
  },
  {
    id: "transform",
    label: "Transform",
    section: "typography",
    keywords: ["transform", "uppercase", "lowercase", "capitalize", "case"],
    input: { type: "tailwind-select", tailwindKey: "transform" },
    sortOrder: 120,
  },
  {
    id: "decoration",
    label: "Decoration",
    section: "typography",
    keywords: [
      "decoration",
      "underline",
      "line-through",
      "strikethrough",
      "overline",
      "style",
      "thickness",
      "wavy",
      "dotted",
      "dashed",
    ],
    sortOrder: 160,
    input: {
      type: "bundle",
      icon: React.createElement(TbUnderline, { className: "size-3.5" }),
      properties: [
        {
          id: "textDecoration",
          label: "Line",
          section: "typography",
          keywords: ["decoration", "underline", "line-through", "strikethrough", "overline"],
          input: { type: "tailwind-select", tailwindKey: "textDecoration" },
          inline: true,
        },
        {
          id: "decorationStyle",
          label: "Style",
          section: "typography",
          keywords: ["decoration", "style", "solid", "double", "dotted", "dashed", "wavy"],
          input: { type: "tailwind-select", tailwindKey: "decorationStyle" },
          inline: true,
        },
        {
          id: "decorationThickness",
          label: "Thickness",
          section: "typography",
          keywords: ["decoration", "thickness", "size", "width"],
          input: { type: "tailwind-select", tailwindKey: "decorationThickness" },
          inline: true,
        },
      ],
    },
  },
  {
    id: "emphasis",
    label: "Style",
    section: "typography",
    keywords: ["bold", "italic", "underline", "strike", "style", "emphasis", "weight"],
    sortOrder: 190,
    inline: true,
    input: {
      type: "multi-toggle",
      toggles: [
        {
          icon: React.createElement(TbBold, { className: "size-3.5" }),
          tooltip: "Bold",
          propKey: "fontWeight",
          className: "font-bold",
        },
        {
          icon: React.createElement(TbItalic, { className: "size-3.5" }),
          tooltip: "Italic",
          propKey: "fontStyle",
          className: "italic",
        },
        {
          icon: React.createElement(TbUnderline, { className: "size-3.5" }),
          tooltip: "Underline",
          propKey: "textDecoration",
          className: "underline",
        },
        {
          icon: React.createElement(TbStrikethrough, { className: "size-3.5" }),
          tooltip: "Strikethrough",
          propKey: "textDecoration",
          className: "line-through",
        },
      ],
    },
  },

  // ─── Wrap & Overflow (bundle) ────────────────────────────────────
  {
    id: "wrap",
    label: "Wrap & Overflow",
    section: "typography",
    keywords: [
      "wrap",
      "overflow",
      "white",
      "space",
      "nowrap",
      "balance",
      "pretty",
      "word",
      "break",
      "ellipsis",
      "truncate",
      "clip",
      "hyphens",
      "hyphenation",
    ],
    sortOrder: 200,
    input: {
      type: "bundle",
      icon: React.createElement(TbTextWrap, { className: "size-3.5" }),
      properties: [
        {
          id: "whiteSpace",
          label: "White Space",
          section: "typography",
          keywords: ["white", "space", "nowrap", "pre", "wrap"],
          input: {
            type: "select",
            options: [
              { label: "Normal", value: "whitespace-normal" },
              { label: "No Wrap", value: "whitespace-nowrap" },
              { label: "Preserve", value: "whitespace-pre" },
              { label: "Preserve & Wrap", value: "whitespace-pre-wrap" },
              { label: "Preserve Breaks", value: "whitespace-pre-line" },
              { label: "Break Spaces", value: "whitespace-break-spaces" },
            ],
          },
          inline: true,
        },
        {
          id: "textWrap",
          label: "Wrap",
          section: "typography",
          keywords: ["wrap", "balance", "pretty", "nowrap"],
          input: { type: "tailwind-select", tailwindKey: "textWrap" },
          inline: true,
        },
        {
          id: "wordBreak",
          label: "Word Break",
          section: "typography",
          keywords: ["word", "break", "wrap", "overflow"],
          input: {
            type: "select",
            options: [
              { label: "Normal", value: "break-normal" },
              { label: "Break Long Words", value: "break-words" },
              { label: "Break Anywhere", value: "break-all" },
              { label: "Keep Together", value: "break-keep" },
            ],
          },
          inline: true,
        },
        {
          id: "textOverflow",
          label: "Overflow",
          section: "typography",
          keywords: ["overflow", "ellipsis", "truncate", "clip"],
          input: { type: "tailwind-select", tailwindKey: "textOverflow" },
          inline: true,
        },
        {
          id: "hyphens",
          label: "Hyphens",
          section: "typography",
          keywords: ["hyphens", "hyphenation", "break"],
          input: { type: "tailwind-select", tailwindKey: "hyphens" },
          inline: true,
        },
      ],
    },
  },
];
