/**
 * Typography property definitions — pure data, no JSX, no imports of inputs.
 * Custom inputs are referenced by string key into the customInputs registry.
 */
import type { PropertyDef } from "../propertyDefs";

export const typographyProperties: PropertyDef[] = [
  {
    id: "typographyPreset",
    label: "Preset",
    section: "typography",
    keywords: ["preset", "typography", "style", "heading", "body", "accent"],
    input: { type: "custom", component: "TypographyPresetInput" },
    pinned: true,
    sortOrder: -10,
    inline: true,
  },
  {
    id: "textAlign",
    label: "Text Align",
    section: "typography",
    keywords: ["align", "left", "center", "right", "justify", "start", "end"],
    input: { type: "tailwind-radio", tailwindKey: "textAlign", cols: true },
    sortOrder: 0,
  },
  {
    id: "fontFamily",
    label: "Family",
    section: "typography",
    keywords: ["font", "family", "typeface", "google", "heading", "body", "accent"],
    input: { type: "custom", component: "FontFamilyInput" },
    sortOrder: 10,
  },
  {
    id: "fontSize",
    label: "Size",
    section: "typography",
    keywords: ["size", "text", "large", "small", "xl", "2xl", "3xl"],
    input: {
      type: "tailwind-select",
      tailwindKey: "fontSize",
      showVarSelector: true,
      varSelectorPrefix: "text",
    },
    sortOrder: 20,
  },
  {
    id: "fontWeight",
    label: "Weight",
    section: "typography",
    keywords: ["weight", "bold", "light", "semibold", "thin", "medium", "heavy"],
    input: {
      type: "tailwind-select",
      tailwindKey: "fontWeight",
      showVarSelector: true,
      varSelectorPrefix: "font",
    },
    sortOrder: 30,
  },
  {
    id: "textColor",
    label: "Color",
    section: "typography",
    keywords: ["color", "text", "foreground", "font color"],
    input: { type: "color", prefix: "text" },
    hideKey: "textColor",
    sortOrder: 40,
    inline: true,
  },

  // Hidden until added (formerly behind "More typography" toggle)
  {
    id: "lineHeight",
    label: "Line Height",
    section: "typography",
    keywords: ["line", "height", "leading", "spacing", "vertical"],
    input: { type: "tailwind-select", tailwindKey: "lineHeight" },
    sortOrder: 100,
  },
  {
    id: "tracking",
    label: "Tracking",
    section: "typography",
    keywords: ["tracking", "letter", "spacing", "kerning"],
    input: { type: "tailwind-select", tailwindKey: "tracking" },
    sortOrder: 110,
  },
  {
    id: "transform",
    label: "Transform",
    section: "typography",
    keywords: ["transform", "uppercase", "lowercase", "capitalize", "case"],
    input: { type: "tailwind-select", tailwindKey: "transform" },
    sortOrder: 120,
  },
  {
    id: "wordBreak",
    label: "Word Break",
    section: "typography",
    keywords: ["word", "break", "wrap", "overflow"],
    input: { type: "tailwind-select", tailwindKey: "wordBreak" },
    sortOrder: 130,
  },
  {
    id: "textOverflow",
    label: "Overflow",
    section: "typography",
    keywords: ["overflow", "ellipsis", "truncate", "clip"],
    input: { type: "tailwind-select", tailwindKey: "textOverflow" },
    sortOrder: 140,
  },
  {
    id: "indent",
    label: "Indent",
    section: "typography",
    keywords: ["indent", "paragraph", "first line"],
    input: { type: "tailwind-select", tailwindKey: "indent" },
    sortOrder: 150,
  },
  {
    id: "textDecoration",
    label: "Line",
    section: "typography",
    keywords: ["decoration", "underline", "line-through", "strikethrough", "overline"],
    input: { type: "tailwind-select", tailwindKey: "textDecoration" },
    sortOrder: 160,
  },
  {
    id: "decorationStyle",
    label: "Style",
    section: "typography",
    keywords: ["decoration", "style", "solid", "double", "dotted", "dashed", "wavy"],
    input: { type: "tailwind-select", tailwindKey: "decorationStyle" },
    sortOrder: 170,
  },
  {
    id: "decorationThickness",
    label: "Thickness",
    section: "typography",
    keywords: ["decoration", "thickness", "size", "width"],
    input: { type: "tailwind-select", tailwindKey: "decorationThickness" },
    sortOrder: 180,
  },
  {
    id: "fontStyle",
    label: "Style",
    section: "typography",
    keywords: ["italic", "oblique", "style", "emphasis"],
    input: { type: "tailwind-select", tailwindKey: "fontStyle" },
    sortOrder: 190,
  },
  {
    id: "whiteSpace",
    label: "White Space",
    section: "typography",
    keywords: ["white", "space", "nowrap", "pre", "wrap"],
    input: { type: "tailwind-select", tailwindKey: "whiteSpace" },
    sortOrder: 200,
  },
  {
    id: "textWrap",
    label: "Wrap",
    section: "typography",
    keywords: ["wrap", "balance", "pretty", "nowrap"],
    input: { type: "tailwind-select", tailwindKey: "textWrap" },
    sortOrder: 210,
  },
  {
    id: "hyphens",
    label: "Hyphens",
    section: "typography",
    keywords: ["hyphens", "hyphenation", "break"],
    input: { type: "tailwind-select", tailwindKey: "hyphens" },
    sortOrder: 220,
  },
];
