/**
 * AUTO-GENERATED — run: node scripts/generate-tailwind-styles.js
 *
 * Tailwind style data for dropdown options, validation, and class ↔ prop key mapping.
 * Generated from tailwindcss/defaultTheme + tailwindcss/colors.
 */

import colors from "tailwindcss/colors";
import { ringOutlineClassKey } from "./ringOutlineClassKey";

// ─── RootClassGenProps ─────────────────────────────────────────────────────

// Styling lives on className; keep empty so reverse index maps utilities to panel keys.
export const RootClassGenProps = [];

// ─── Fonts ─────────────────────────────────────────────────────────────────

export const fonts = [
  ["Roboto"], ["Open Sans"], ["Lato"], ["Montserrat"], ["Oswald"],
  ["Raleway"], ["PT Sans"], ["Source Sans Pro"], ["Noto Sans"], ["Merriweather"],
  ["Playfair Display"], ["Nunito"], ["Inter"], ["Rubik"], ["Fira Sans"],
  ["Poppins"], ["Work Sans"], ["Ubuntu"], ["Mukta"], ["Quicksand"],
  ["Karla"], ["Titillium Web"], ["Bitter"], ["Hind"], ["Cabin"],
  ["Crimson Text"], ["Inconsolata"], ["Oxygen"], ["Droid Sans"], ["Josefin Sans"],
  ["EB Garamond"], ["Abel"], ["Lora"], ["Noto Serif"], ["Archivo Narrow"],
  ["Pacifico"], ["Orbitron"], ["Press Start 2P"], ["Permanent Marker"],
  ["Bebas Neue"], ["Russo One"], ["Fredoka One"], ["Lobster"],
  ["Righteous"], ["Indie Flower"],
];

// ─── Color palette helper ──────────────────────────────────────────────────

const colorExclude = ["lightBlue", "warmGray", "trueGray", "coolGray", "blueGray"];

export function getColorPalette() {
  return Object.keys(colors)
    .filter(_ => !colorExclude.includes(_))
    .map(key => {
      const color = typeof colors[key] === "object"
        ? Object.keys(colors[key]).map(_ => ({ key: _, color: colors[key][_] }))
        : null;
      return color ? { key, color } : null;
    })
    .filter(_ => _);
}

// ─── TailwindStyles ────────────────────────────────────────────────────────

export const TailwindStyles = {
  m: [
    "m-0",
    "m-1",
    "m-2",
    "m-3",
    "m-4",
    "m-5",
    "m-6",
    "m-7",
    "m-8",
    "m-9",
    "m-10",
    "m-11",
    "m-12",
    "m-14",
    "m-16",
    "m-20",
    "m-24",
    "m-28",
    "m-32",
    "m-36",
    "m-40",
    "m-44",
    "m-48",
    "m-52",
    "m-56",
    "m-60",
    "m-64",
    "m-72",
    "m-80",
    "m-96",
    "m-px",
    "m-0.5",
    "m-1.5",
    "m-2.5",
    "m-3.5",
  ],
  p: [
    "p-0",
    "p-1",
    "p-2",
    "p-3",
    "p-4",
    "p-5",
    "p-6",
    "p-7",
    "p-8",
    "p-9",
    "p-10",
    "p-11",
    "p-12",
    "p-14",
    "p-16",
    "p-20",
    "p-24",
    "p-28",
    "p-32",
    "p-36",
    "p-40",
    "p-44",
    "p-48",
    "p-52",
    "p-56",
    "p-60",
    "p-64",
    "p-72",
    "p-80",
    "p-96",
    "p-px",
    "p-0.5",
    "p-1.5",
    "p-2.5",
    "p-3.5",
  ],
  gap: [
    "gap-0",
    "gap-1",
    "gap-2",
    "gap-3",
    "gap-4",
    "gap-5",
    "gap-6",
    "gap-7",
    "gap-8",
    "gap-9",
    "gap-10",
    "gap-11",
    "gap-12",
    "gap-14",
    "gap-16",
    "gap-20",
    "gap-24",
    "gap-28",
    "gap-32",
    "gap-36",
    "gap-40",
    "gap-44",
    "gap-48",
    "gap-52",
    "gap-56",
    "gap-60",
    "gap-64",
    "gap-72",
    "gap-80",
    "gap-96",
    "gap-px",
    "gap-0.5",
    "gap-1.5",
    "gap-2.5",
    "gap-3.5",
  ],
  mx: [
    "mx-0",
    "mx-1",
    "mx-2",
    "mx-3",
    "mx-4",
    "mx-5",
    "mx-6",
    "mx-7",
    "mx-8",
    "mx-9",
    "mx-10",
    "mx-11",
    "mx-12",
    "mx-14",
    "mx-16",
    "mx-20",
    "mx-24",
    "mx-28",
    "mx-32",
    "mx-36",
    "mx-40",
    "mx-44",
    "mx-48",
    "mx-52",
    "mx-56",
    "mx-60",
    "mx-64",
    "mx-72",
    "mx-80",
    "mx-96",
    "mx-px",
    "mx-0.5",
    "mx-1.5",
    "mx-2.5",
    "mx-3.5",
  ],
  my: [
    "my-0",
    "my-1",
    "my-2",
    "my-3",
    "my-4",
    "my-5",
    "my-6",
    "my-7",
    "my-8",
    "my-9",
    "my-10",
    "my-11",
    "my-12",
    "my-14",
    "my-16",
    "my-20",
    "my-24",
    "my-28",
    "my-32",
    "my-36",
    "my-40",
    "my-44",
    "my-48",
    "my-52",
    "my-56",
    "my-60",
    "my-64",
    "my-72",
    "my-80",
    "my-96",
    "my-px",
    "my-0.5",
    "my-1.5",
    "my-2.5",
    "my-3.5",
  ],
  px: [
    "px-0",
    "px-1",
    "px-2",
    "px-3",
    "px-4",
    "px-5",
    "px-6",
    "px-7",
    "px-8",
    "px-9",
    "px-10",
    "px-11",
    "px-12",
    "px-14",
    "px-16",
    "px-20",
    "px-24",
    "px-28",
    "px-32",
    "px-36",
    "px-40",
    "px-44",
    "px-48",
    "px-52",
    "px-56",
    "px-60",
    "px-64",
    "px-72",
    "px-80",
    "px-96",
    "px-px",
    "px-0.5",
    "px-1.5",
    "px-2.5",
    "px-3.5",
  ],
  py: [
    "py-0",
    "py-1",
    "py-2",
    "py-3",
    "py-4",
    "py-5",
    "py-6",
    "py-7",
    "py-8",
    "py-9",
    "py-10",
    "py-11",
    "py-12",
    "py-14",
    "py-16",
    "py-20",
    "py-24",
    "py-28",
    "py-32",
    "py-36",
    "py-40",
    "py-44",
    "py-48",
    "py-52",
    "py-56",
    "py-60",
    "py-64",
    "py-72",
    "py-80",
    "py-96",
    "py-px",
    "py-0.5",
    "py-1.5",
    "py-2.5",
    "py-3.5",
  ],
  ml: [
    "ml-0",
    "ml-1",
    "ml-2",
    "ml-3",
    "ml-4",
    "ml-5",
    "ml-6",
    "ml-7",
    "ml-8",
    "ml-9",
    "ml-10",
    "ml-11",
    "ml-12",
    "ml-14",
    "ml-16",
    "ml-20",
    "ml-24",
    "ml-28",
    "ml-32",
    "ml-36",
    "ml-40",
    "ml-44",
    "ml-48",
    "ml-52",
    "ml-56",
    "ml-60",
    "ml-64",
    "ml-72",
    "ml-80",
    "ml-96",
    "ml-px",
    "ml-0.5",
    "ml-1.5",
    "ml-2.5",
    "ml-3.5",
    "-ml-1",
    "-ml-2",
    "-ml-3",
    "-ml-4",
    "-ml-5",
    "-ml-6",
    "-ml-7",
    "-ml-8",
    "-ml-9",
    "-ml-10",
    "-ml-11",
    "-ml-12",
    "-ml-14",
    "-ml-16",
    "-ml-20",
    "-ml-24",
    "-ml-28",
    "-ml-32",
    "-ml-36",
    "-ml-40",
    "-ml-44",
    "-ml-48",
    "-ml-52",
    "-ml-56",
    "-ml-60",
    "-ml-64",
    "-ml-72",
    "-ml-80",
    "-ml-96",
    "-ml-0.5",
    "-ml-1.5",
    "-ml-2.5",
    "-ml-3.5",
  ],
  mr: [
    "mr-0",
    "mr-1",
    "mr-2",
    "mr-3",
    "mr-4",
    "mr-5",
    "mr-6",
    "mr-7",
    "mr-8",
    "mr-9",
    "mr-10",
    "mr-11",
    "mr-12",
    "mr-14",
    "mr-16",
    "mr-20",
    "mr-24",
    "mr-28",
    "mr-32",
    "mr-36",
    "mr-40",
    "mr-44",
    "mr-48",
    "mr-52",
    "mr-56",
    "mr-60",
    "mr-64",
    "mr-72",
    "mr-80",
    "mr-96",
    "mr-px",
    "mr-0.5",
    "mr-1.5",
    "mr-2.5",
    "mr-3.5",
    "-mr-1",
    "-mr-2",
    "-mr-3",
    "-mr-4",
    "-mr-5",
    "-mr-6",
    "-mr-7",
    "-mr-8",
    "-mr-9",
    "-mr-10",
    "-mr-11",
    "-mr-12",
    "-mr-14",
    "-mr-16",
    "-mr-20",
    "-mr-24",
    "-mr-28",
    "-mr-32",
    "-mr-36",
    "-mr-40",
    "-mr-44",
    "-mr-48",
    "-mr-52",
    "-mr-56",
    "-mr-60",
    "-mr-64",
    "-mr-72",
    "-mr-80",
    "-mr-96",
    "-mr-0.5",
    "-mr-1.5",
    "-mr-2.5",
    "-mr-3.5",
  ],
  mt: [
    "mt-0",
    "mt-1",
    "mt-2",
    "mt-3",
    "mt-4",
    "mt-5",
    "mt-6",
    "mt-7",
    "mt-8",
    "mt-9",
    "mt-10",
    "mt-11",
    "mt-12",
    "mt-14",
    "mt-16",
    "mt-20",
    "mt-24",
    "mt-28",
    "mt-32",
    "mt-36",
    "mt-40",
    "mt-44",
    "mt-48",
    "mt-52",
    "mt-56",
    "mt-60",
    "mt-64",
    "mt-72",
    "mt-80",
    "mt-96",
    "mt-px",
    "mt-0.5",
    "mt-1.5",
    "mt-2.5",
    "mt-3.5",
    "-mt-1",
    "-mt-2",
    "-mt-3",
    "-mt-4",
    "-mt-5",
    "-mt-6",
    "-mt-7",
    "-mt-8",
    "-mt-9",
    "-mt-10",
    "-mt-11",
    "-mt-12",
    "-mt-14",
    "-mt-16",
    "-mt-20",
    "-mt-24",
    "-mt-28",
    "-mt-32",
    "-mt-36",
    "-mt-40",
    "-mt-44",
    "-mt-48",
    "-mt-52",
    "-mt-56",
    "-mt-60",
    "-mt-64",
    "-mt-72",
    "-mt-80",
    "-mt-96",
    "-mt-0.5",
    "-mt-1.5",
    "-mt-2.5",
    "-mt-3.5",
  ],
  mb: [
    "mb-0",
    "mb-1",
    "mb-2",
    "mb-3",
    "mb-4",
    "mb-5",
    "mb-6",
    "mb-7",
    "mb-8",
    "mb-9",
    "mb-10",
    "mb-11",
    "mb-12",
    "mb-14",
    "mb-16",
    "mb-20",
    "mb-24",
    "mb-28",
    "mb-32",
    "mb-36",
    "mb-40",
    "mb-44",
    "mb-48",
    "mb-52",
    "mb-56",
    "mb-60",
    "mb-64",
    "mb-72",
    "mb-80",
    "mb-96",
    "mb-px",
    "mb-0.5",
    "mb-1.5",
    "mb-2.5",
    "mb-3.5",
    "-mb-1",
    "-mb-2",
    "-mb-3",
    "-mb-4",
    "-mb-5",
    "-mb-6",
    "-mb-7",
    "-mb-8",
    "-mb-9",
    "-mb-10",
    "-mb-11",
    "-mb-12",
    "-mb-14",
    "-mb-16",
    "-mb-20",
    "-mb-24",
    "-mb-28",
    "-mb-32",
    "-mb-36",
    "-mb-40",
    "-mb-44",
    "-mb-48",
    "-mb-52",
    "-mb-56",
    "-mb-60",
    "-mb-64",
    "-mb-72",
    "-mb-80",
    "-mb-96",
    "-mb-0.5",
    "-mb-1.5",
    "-mb-2.5",
    "-mb-3.5",
  ],
  pl: [
    "pl-0",
    "pl-1",
    "pl-2",
    "pl-3",
    "pl-4",
    "pl-5",
    "pl-6",
    "pl-7",
    "pl-8",
    "pl-9",
    "pl-10",
    "pl-11",
    "pl-12",
    "pl-14",
    "pl-16",
    "pl-20",
    "pl-24",
    "pl-28",
    "pl-32",
    "pl-36",
    "pl-40",
    "pl-44",
    "pl-48",
    "pl-52",
    "pl-56",
    "pl-60",
    "pl-64",
    "pl-72",
    "pl-80",
    "pl-96",
    "pl-px",
    "pl-0.5",
    "pl-1.5",
    "pl-2.5",
    "pl-3.5",
  ],
  pr: [
    "pr-0",
    "pr-1",
    "pr-2",
    "pr-3",
    "pr-4",
    "pr-5",
    "pr-6",
    "pr-7",
    "pr-8",
    "pr-9",
    "pr-10",
    "pr-11",
    "pr-12",
    "pr-14",
    "pr-16",
    "pr-20",
    "pr-24",
    "pr-28",
    "pr-32",
    "pr-36",
    "pr-40",
    "pr-44",
    "pr-48",
    "pr-52",
    "pr-56",
    "pr-60",
    "pr-64",
    "pr-72",
    "pr-80",
    "pr-96",
    "pr-px",
    "pr-0.5",
    "pr-1.5",
    "pr-2.5",
    "pr-3.5",
  ],
  pt: [
    "pt-0",
    "pt-1",
    "pt-2",
    "pt-3",
    "pt-4",
    "pt-5",
    "pt-6",
    "pt-7",
    "pt-8",
    "pt-9",
    "pt-10",
    "pt-11",
    "pt-12",
    "pt-14",
    "pt-16",
    "pt-20",
    "pt-24",
    "pt-28",
    "pt-32",
    "pt-36",
    "pt-40",
    "pt-44",
    "pt-48",
    "pt-52",
    "pt-56",
    "pt-60",
    "pt-64",
    "pt-72",
    "pt-80",
    "pt-96",
    "pt-px",
    "pt-0.5",
    "pt-1.5",
    "pt-2.5",
    "pt-3.5",
  ],
  pb: [
    "pb-0",
    "pb-1",
    "pb-2",
    "pb-3",
    "pb-4",
    "pb-5",
    "pb-6",
    "pb-7",
    "pb-8",
    "pb-9",
    "pb-10",
    "pb-11",
    "pb-12",
    "pb-14",
    "pb-16",
    "pb-20",
    "pb-24",
    "pb-28",
    "pb-32",
    "pb-36",
    "pb-40",
    "pb-44",
    "pb-48",
    "pb-52",
    "pb-56",
    "pb-60",
    "pb-64",
    "pb-72",
    "pb-80",
    "pb-96",
    "pb-px",
    "pb-0.5",
    "pb-1.5",
    "pb-2.5",
    "pb-3.5",
  ],
  background: [
    "bg-inherit",
    "bg-current",
    "bg-transparent",
    "bg-black",
    "bg-white",
    "bg-slate-50",
    "bg-slate-100",
    "bg-slate-200",
    "bg-slate-300",
    "bg-slate-400",
    "bg-slate-500",
    "bg-slate-600",
    "bg-slate-700",
    "bg-slate-800",
    "bg-slate-900",
    "bg-slate-950",
    "bg-gray-50",
    "bg-gray-100",
    "bg-gray-200",
    "bg-gray-300",
    "bg-gray-400",
    "bg-gray-500",
    "bg-gray-600",
    "bg-gray-700",
    "bg-gray-800",
    "bg-gray-900",
    "bg-gray-950",
    "bg-zinc-50",
    "bg-zinc-100",
    "bg-zinc-200",
    "bg-zinc-300",
    "bg-zinc-400",
    "bg-zinc-500",
    "bg-zinc-600",
    "bg-zinc-700",
    "bg-zinc-800",
    "bg-zinc-900",
    "bg-zinc-950",
    "bg-neutral-50",
    "bg-neutral-100",
    "bg-neutral-200",
    "bg-neutral-300",
    "bg-neutral-400",
    "bg-neutral-500",
    "bg-neutral-600",
    "bg-neutral-700",
    "bg-neutral-800",
    "bg-neutral-900",
    "bg-neutral-950",
    "bg-stone-50",
    "bg-stone-100",
    "bg-stone-200",
    "bg-stone-300",
    "bg-stone-400",
    "bg-stone-500",
    "bg-stone-600",
    "bg-stone-700",
    "bg-stone-800",
    "bg-stone-900",
    "bg-stone-950",
    "bg-mauve-50",
    "bg-mauve-100",
    "bg-mauve-200",
    "bg-mauve-300",
    "bg-mauve-400",
    "bg-mauve-500",
    "bg-mauve-600",
    "bg-mauve-700",
    "bg-mauve-800",
    "bg-mauve-900",
    "bg-mauve-950",
    "bg-olive-50",
    "bg-olive-100",
    "bg-olive-200",
    "bg-olive-300",
    "bg-olive-400",
    "bg-olive-500",
    "bg-olive-600",
    "bg-olive-700",
    "bg-olive-800",
    "bg-olive-900",
    "bg-olive-950",
    "bg-mist-50",
    "bg-mist-100",
    "bg-mist-200",
    "bg-mist-300",
    "bg-mist-400",
    "bg-mist-500",
    "bg-mist-600",
    "bg-mist-700",
    "bg-mist-800",
    "bg-mist-900",
    "bg-mist-950",
    "bg-taupe-50",
    "bg-taupe-100",
    "bg-taupe-200",
    "bg-taupe-300",
    "bg-taupe-400",
    "bg-taupe-500",
    "bg-taupe-600",
    "bg-taupe-700",
    "bg-taupe-800",
    "bg-taupe-900",
    "bg-taupe-950",
    "bg-red-50",
    "bg-red-100",
    "bg-red-200",
    "bg-red-300",
    "bg-red-400",
    "bg-red-500",
    "bg-red-600",
    "bg-red-700",
    "bg-red-800",
    "bg-red-900",
    "bg-red-950",
    "bg-orange-50",
    "bg-orange-100",
    "bg-orange-200",
    "bg-orange-300",
    "bg-orange-400",
    "bg-orange-500",
    "bg-orange-600",
    "bg-orange-700",
    "bg-orange-800",
    "bg-orange-900",
    "bg-orange-950",
    "bg-amber-50",
    "bg-amber-100",
    "bg-amber-200",
    "bg-amber-300",
    "bg-amber-400",
    "bg-amber-500",
    "bg-amber-600",
    "bg-amber-700",
    "bg-amber-800",
    "bg-amber-900",
    "bg-amber-950",
    "bg-yellow-50",
    "bg-yellow-100",
    "bg-yellow-200",
    "bg-yellow-300",
    "bg-yellow-400",
    "bg-yellow-500",
    "bg-yellow-600",
    "bg-yellow-700",
    "bg-yellow-800",
    "bg-yellow-900",
    "bg-yellow-950",
    "bg-lime-50",
    "bg-lime-100",
    "bg-lime-200",
    "bg-lime-300",
    "bg-lime-400",
    "bg-lime-500",
    "bg-lime-600",
    "bg-lime-700",
    "bg-lime-800",
    "bg-lime-900",
    "bg-lime-950",
    "bg-green-50",
    "bg-green-100",
    "bg-green-200",
    "bg-green-300",
    "bg-green-400",
    "bg-green-500",
    "bg-green-600",
    "bg-green-700",
    "bg-green-800",
    "bg-green-900",
    "bg-green-950",
    "bg-emerald-50",
    "bg-emerald-100",
    "bg-emerald-200",
    "bg-emerald-300",
    "bg-emerald-400",
    "bg-emerald-500",
    "bg-emerald-600",
    "bg-emerald-700",
    "bg-emerald-800",
    "bg-emerald-900",
    "bg-emerald-950",
    "bg-teal-50",
    "bg-teal-100",
    "bg-teal-200",
    "bg-teal-300",
    "bg-teal-400",
    "bg-teal-500",
    "bg-teal-600",
    "bg-teal-700",
    "bg-teal-800",
    "bg-teal-900",
    "bg-teal-950",
    "bg-cyan-50",
    "bg-cyan-100",
    "bg-cyan-200",
    "bg-cyan-300",
    "bg-cyan-400",
    "bg-cyan-500",
    "bg-cyan-600",
    "bg-cyan-700",
    "bg-cyan-800",
    "bg-cyan-900",
    "bg-cyan-950",
    "bg-sky-50",
    "bg-sky-100",
    "bg-sky-200",
    "bg-sky-300",
    "bg-sky-400",
    "bg-sky-500",
    "bg-sky-600",
    "bg-sky-700",
    "bg-sky-800",
    "bg-sky-900",
    "bg-sky-950",
    "bg-blue-50",
    "bg-blue-100",
    "bg-blue-200",
    "bg-blue-300",
    "bg-blue-400",
    "bg-blue-500",
    "bg-blue-600",
    "bg-blue-700",
    "bg-blue-800",
    "bg-blue-900",
    "bg-blue-950",
    "bg-indigo-50",
    "bg-indigo-100",
    "bg-indigo-200",
    "bg-indigo-300",
    "bg-indigo-400",
    "bg-indigo-500",
    "bg-indigo-600",
    "bg-indigo-700",
    "bg-indigo-800",
    "bg-indigo-900",
    "bg-indigo-950",
    "bg-violet-50",
    "bg-violet-100",
    "bg-violet-200",
    "bg-violet-300",
    "bg-violet-400",
    "bg-violet-500",
    "bg-violet-600",
    "bg-violet-700",
    "bg-violet-800",
    "bg-violet-900",
    "bg-violet-950",
    "bg-purple-50",
    "bg-purple-100",
    "bg-purple-200",
    "bg-purple-300",
    "bg-purple-400",
    "bg-purple-500",
    "bg-purple-600",
    "bg-purple-700",
    "bg-purple-800",
    "bg-purple-900",
    "bg-purple-950",
    "bg-fuchsia-50",
    "bg-fuchsia-100",
    "bg-fuchsia-200",
    "bg-fuchsia-300",
    "bg-fuchsia-400",
    "bg-fuchsia-500",
    "bg-fuchsia-600",
    "bg-fuchsia-700",
    "bg-fuchsia-800",
    "bg-fuchsia-900",
    "bg-fuchsia-950",
    "bg-pink-50",
    "bg-pink-100",
    "bg-pink-200",
    "bg-pink-300",
    "bg-pink-400",
    "bg-pink-500",
    "bg-pink-600",
    "bg-pink-700",
    "bg-pink-800",
    "bg-pink-900",
    "bg-pink-950",
    "bg-rose-50",
    "bg-rose-100",
    "bg-rose-200",
    "bg-rose-300",
    "bg-rose-400",
    "bg-rose-500",
    "bg-rose-600",
    "bg-rose-700",
    "bg-rose-800",
    "bg-rose-900",
    "bg-rose-950",
  ],
  text: [
    "text-inherit",
    "text-current",
    "text-transparent",
    "text-black",
    "text-white",
    "text-slate-50",
    "text-slate-100",
    "text-slate-200",
    "text-slate-300",
    "text-slate-400",
    "text-slate-500",
    "text-slate-600",
    "text-slate-700",
    "text-slate-800",
    "text-slate-900",
    "text-slate-950",
    "text-gray-50",
    "text-gray-100",
    "text-gray-200",
    "text-gray-300",
    "text-gray-400",
    "text-gray-500",
    "text-gray-600",
    "text-gray-700",
    "text-gray-800",
    "text-gray-900",
    "text-gray-950",
    "text-zinc-50",
    "text-zinc-100",
    "text-zinc-200",
    "text-zinc-300",
    "text-zinc-400",
    "text-zinc-500",
    "text-zinc-600",
    "text-zinc-700",
    "text-zinc-800",
    "text-zinc-900",
    "text-zinc-950",
    "text-neutral-50",
    "text-neutral-100",
    "text-neutral-200",
    "text-neutral-300",
    "text-neutral-400",
    "text-neutral-500",
    "text-neutral-600",
    "text-neutral-700",
    "text-neutral-800",
    "text-neutral-900",
    "text-neutral-950",
    "text-stone-50",
    "text-stone-100",
    "text-stone-200",
    "text-stone-300",
    "text-stone-400",
    "text-stone-500",
    "text-stone-600",
    "text-stone-700",
    "text-stone-800",
    "text-stone-900",
    "text-stone-950",
    "text-mauve-50",
    "text-mauve-100",
    "text-mauve-200",
    "text-mauve-300",
    "text-mauve-400",
    "text-mauve-500",
    "text-mauve-600",
    "text-mauve-700",
    "text-mauve-800",
    "text-mauve-900",
    "text-mauve-950",
    "text-olive-50",
    "text-olive-100",
    "text-olive-200",
    "text-olive-300",
    "text-olive-400",
    "text-olive-500",
    "text-olive-600",
    "text-olive-700",
    "text-olive-800",
    "text-olive-900",
    "text-olive-950",
    "text-mist-50",
    "text-mist-100",
    "text-mist-200",
    "text-mist-300",
    "text-mist-400",
    "text-mist-500",
    "text-mist-600",
    "text-mist-700",
    "text-mist-800",
    "text-mist-900",
    "text-mist-950",
    "text-taupe-50",
    "text-taupe-100",
    "text-taupe-200",
    "text-taupe-300",
    "text-taupe-400",
    "text-taupe-500",
    "text-taupe-600",
    "text-taupe-700",
    "text-taupe-800",
    "text-taupe-900",
    "text-taupe-950",
    "text-red-50",
    "text-red-100",
    "text-red-200",
    "text-red-300",
    "text-red-400",
    "text-red-500",
    "text-red-600",
    "text-red-700",
    "text-red-800",
    "text-red-900",
    "text-red-950",
    "text-orange-50",
    "text-orange-100",
    "text-orange-200",
    "text-orange-300",
    "text-orange-400",
    "text-orange-500",
    "text-orange-600",
    "text-orange-700",
    "text-orange-800",
    "text-orange-900",
    "text-orange-950",
    "text-amber-50",
    "text-amber-100",
    "text-amber-200",
    "text-amber-300",
    "text-amber-400",
    "text-amber-500",
    "text-amber-600",
    "text-amber-700",
    "text-amber-800",
    "text-amber-900",
    "text-amber-950",
    "text-yellow-50",
    "text-yellow-100",
    "text-yellow-200",
    "text-yellow-300",
    "text-yellow-400",
    "text-yellow-500",
    "text-yellow-600",
    "text-yellow-700",
    "text-yellow-800",
    "text-yellow-900",
    "text-yellow-950",
    "text-lime-50",
    "text-lime-100",
    "text-lime-200",
    "text-lime-300",
    "text-lime-400",
    "text-lime-500",
    "text-lime-600",
    "text-lime-700",
    "text-lime-800",
    "text-lime-900",
    "text-lime-950",
    "text-green-50",
    "text-green-100",
    "text-green-200",
    "text-green-300",
    "text-green-400",
    "text-green-500",
    "text-green-600",
    "text-green-700",
    "text-green-800",
    "text-green-900",
    "text-green-950",
    "text-emerald-50",
    "text-emerald-100",
    "text-emerald-200",
    "text-emerald-300",
    "text-emerald-400",
    "text-emerald-500",
    "text-emerald-600",
    "text-emerald-700",
    "text-emerald-800",
    "text-emerald-900",
    "text-emerald-950",
    "text-teal-50",
    "text-teal-100",
    "text-teal-200",
    "text-teal-300",
    "text-teal-400",
    "text-teal-500",
    "text-teal-600",
    "text-teal-700",
    "text-teal-800",
    "text-teal-900",
    "text-teal-950",
    "text-cyan-50",
    "text-cyan-100",
    "text-cyan-200",
    "text-cyan-300",
    "text-cyan-400",
    "text-cyan-500",
    "text-cyan-600",
    "text-cyan-700",
    "text-cyan-800",
    "text-cyan-900",
    "text-cyan-950",
    "text-sky-50",
    "text-sky-100",
    "text-sky-200",
    "text-sky-300",
    "text-sky-400",
    "text-sky-500",
    "text-sky-600",
    "text-sky-700",
    "text-sky-800",
    "text-sky-900",
    "text-sky-950",
    "text-blue-50",
    "text-blue-100",
    "text-blue-200",
    "text-blue-300",
    "text-blue-400",
    "text-blue-500",
    "text-blue-600",
    "text-blue-700",
    "text-blue-800",
    "text-blue-900",
    "text-blue-950",
    "text-indigo-50",
    "text-indigo-100",
    "text-indigo-200",
    "text-indigo-300",
    "text-indigo-400",
    "text-indigo-500",
    "text-indigo-600",
    "text-indigo-700",
    "text-indigo-800",
    "text-indigo-900",
    "text-indigo-950",
    "text-violet-50",
    "text-violet-100",
    "text-violet-200",
    "text-violet-300",
    "text-violet-400",
    "text-violet-500",
    "text-violet-600",
    "text-violet-700",
    "text-violet-800",
    "text-violet-900",
    "text-violet-950",
    "text-purple-50",
    "text-purple-100",
    "text-purple-200",
    "text-purple-300",
    "text-purple-400",
    "text-purple-500",
    "text-purple-600",
    "text-purple-700",
    "text-purple-800",
    "text-purple-900",
    "text-purple-950",
    "text-fuchsia-50",
    "text-fuchsia-100",
    "text-fuchsia-200",
    "text-fuchsia-300",
    "text-fuchsia-400",
    "text-fuchsia-500",
    "text-fuchsia-600",
    "text-fuchsia-700",
    "text-fuchsia-800",
    "text-fuchsia-900",
    "text-fuchsia-950",
    "text-pink-50",
    "text-pink-100",
    "text-pink-200",
    "text-pink-300",
    "text-pink-400",
    "text-pink-500",
    "text-pink-600",
    "text-pink-700",
    "text-pink-800",
    "text-pink-900",
    "text-pink-950",
    "text-rose-50",
    "text-rose-100",
    "text-rose-200",
    "text-rose-300",
    "text-rose-400",
    "text-rose-500",
    "text-rose-600",
    "text-rose-700",
    "text-rose-800",
    "text-rose-900",
    "text-rose-950",
  ],
  backgroundRepeat: [
    "bg-repeat",
    "bg-no-repeat",
    "bg-repeat-x",
    "bg-repeat-y",
    "bg-repeat-round",
    "bg-repeat-space",
  ],
  backgroundSize: ["bg-auto", "bg-cover", "bg-contain"],
  backgroundAttachment: ["bg-fixed", "bg-local", "bg-scroll"],
  backgroundOrigin: ["bg-origin-border", "bg-origin-padding", "bg-origin-content"],
  backgroundPosition: [
    "bg-bottom",
    "bg-center",
    "bg-left",
    "bg-bottom-left",
    "bg-top-left",
    "bg-right",
    "bg-bottom-right",
    "bg-top-right",
    "bg-top",
  ],
  gradients: [
    "bg-linear-to-t",
    "bg-linear-to-tr",
    "bg-linear-to-r",
    "bg-linear-to-br",
    "bg-linear-to-b",
    "bg-linear-to-bl",
    "bg-linear-to-l",
    "bg-linear-to-tl",
  ],
  fontSize: [
    "text-xs",
    "text-sm",
    "text-base",
    "text-lg",
    "text-xl",
    "text-2xl",
    "text-3xl",
    "text-4xl",
    "text-5xl",
    "text-6xl",
    "text-7xl",
    "text-8xl",
    "text-9xl",
  ],
  fontWeight: [
    "font-thin",
    "font-extralight",
    "font-light",
    "font-normal",
    "font-medium",
    "font-semibold",
    "font-bold",
    "font-extrabold",
    "font-black",
  ],
  lineHeight: [
    "leading-3",
    "leading-4",
    "leading-5",
    "leading-6",
    "leading-7",
    "leading-8",
    "leading-9",
    "leading-10",
    "leading-none",
    "leading-tight",
    "leading-snug",
    "leading-normal",
    "leading-relaxed",
    "leading-loose",
  ],
  tracking: [
    "tracking-tighter",
    "tracking-tight",
    "tracking-normal",
    "tracking-wide",
    "tracking-wider",
    "tracking-widest",
  ],
  radius: [
    "rounded-none",
    "rounded-sm",
    "rounded",
    "rounded-md",
    "rounded-lg",
    "rounded-xl",
    "rounded-2xl",
    "rounded-3xl",
    "rounded-full",
  ],
  border: [
    "border",
    "border-2",
    "border-4",
    "border-8",
  ],
  borderStyle: [
    "border-solid",
    "border-dashed",
    "border-dotted",
    "border-double",
    "border-hidden",
    "border-none",
  ],
  ringWidth: [
    "ring-0",
    "ring-1",
    "ring-2",
    "ring-4",
    "ring-8",
    "ring",
    "ring-inset",
  ],
  outlineWidth: [
    "outline-0",
    "outline-1",
    "outline-2",
    "outline-4",
    "outline-8",
    "outline",
    "outline-none",
    "outline-dashed",
    "outline-dotted",
    "outline-double",
    "outline-hidden",
  ],
  ringOffsetWidth: [
    "ring-offset-0",
    "ring-offset-1",
    "ring-offset-2",
    "ring-offset-4",
    "ring-offset-8",
    "ring-offset",
  ],
  outlineOffset: [
    "outline-offset-0",
    "outline-offset-1",
    "outline-offset-2",
    "outline-offset-4",
    "outline-offset-8",
    "outline-offset",
  ],
  shadow: [
    "shadow-sm",
    "shadow",
    "shadow-md",
    "shadow-lg",
    "shadow-xl",
    "shadow-2xl",
    "shadow-inner",
    "shadow-none",
  ],
  dropShadows: [
    "drop-shadow-none",
    "drop-shadow-sm",
    "drop-shadow-md",
    "drop-shadow-xl",
    "drop-shadow-2xl",
  ],
  width: [
    "w-0",
    "w-1",
    "w-2",
    "w-3",
    "w-4",
    "w-5",
    "w-6",
    "w-7",
    "w-8",
    "w-9",
    "w-10",
    "w-11",
    "w-12",
    "w-14",
    "w-16",
    "w-20",
    "w-24",
    "w-28",
    "w-32",
    "w-36",
    "w-40",
    "w-44",
    "w-48",
    "w-52",
    "w-56",
    "w-60",
    "w-64",
    "w-72",
    "w-80",
    "w-96",
    "w-px",
    "w-0.5",
    "w-1.5",
    "w-2.5",
    "w-3.5",
    "w-auto",
    "w-full",
    "w-screen",
    "w-min",
    "w-max",
    "w-fit",
    "w-1/2",
    "w-1/3",
    "w-2/3",
    "w-1/4",
    "w-2/4",
    "w-3/4",
    "w-1/5",
    "w-2/5",
    "w-3/5",
    "w-4/5",
    "w-1/6",
    "w-5/6",
    "w-1/12",
    "w-2/12",
    "w-3/12",
    "w-4/12",
    "w-5/12",
    "w-6/12",
    "w-7/12",
    "w-8/12",
    "w-9/12",
    "w-10/12",
    "w-11/12",
  ],
  allWidths: [
    "w-0",
    "w-1",
    "w-2",
    "w-3",
    "w-4",
    "w-5",
    "w-6",
    "w-7",
    "w-8",
    "w-9",
    "w-10",
    "w-11",
    "w-12",
    "w-14",
    "w-16",
    "w-20",
    "w-24",
    "w-28",
    "w-32",
    "w-36",
    "w-40",
    "w-44",
    "w-48",
    "w-52",
    "w-56",
    "w-60",
    "w-64",
    "w-72",
    "w-80",
    "w-96",
    "w-px",
    "w-0.5",
    "w-1.5",
    "w-2.5",
    "w-3.5",
    "w-auto",
    "w-full",
    "w-screen",
    "w-min",
    "w-max",
    "w-fit",
    "w-1/2",
    "w-1/3",
    "w-2/3",
    "w-1/4",
    "w-2/4",
    "w-3/4",
    "w-1/5",
    "w-2/5",
    "w-3/5",
    "w-4/5",
    "w-1/6",
    "w-5/6",
    "w-1/12",
    "w-2/12",
    "w-3/12",
    "w-4/12",
    "w-5/12",
    "w-6/12",
    "w-7/12",
    "w-8/12",
    "w-9/12",
    "w-10/12",
    "w-11/12",
  ],
  height: [
    "h-0",
    "h-1",
    "h-2",
    "h-3",
    "h-4",
    "h-5",
    "h-6",
    "h-7",
    "h-8",
    "h-9",
    "h-10",
    "h-11",
    "h-12",
    "h-14",
    "h-16",
    "h-20",
    "h-24",
    "h-28",
    "h-32",
    "h-36",
    "h-40",
    "h-44",
    "h-48",
    "h-52",
    "h-56",
    "h-60",
    "h-64",
    "h-72",
    "h-80",
    "h-96",
    "h-px",
    "h-0.5",
    "h-1.5",
    "h-2.5",
    "h-3.5",
    "h-auto",
    "h-full",
    "h-screen",
    "h-min",
    "h-max",
    "h-fit",
  ],
  maxWidths: [
    "max-w-0",
    "max-w-none",
    "max-w-full",
    "max-w-min",
    "max-w-max",
    "max-w-fit",
    "max-w-prose",
  ],
  maxHeights: [
    "max-h-0",
    "max-h-1",
    "max-h-2",
    "max-h-3",
    "max-h-4",
    "max-h-5",
    "max-h-6",
    "max-h-7",
    "max-h-8",
    "max-h-9",
    "max-h-10",
    "max-h-11",
    "max-h-12",
    "max-h-14",
    "max-h-16",
    "max-h-20",
    "max-h-24",
    "max-h-28",
    "max-h-32",
    "max-h-36",
    "max-h-40",
    "max-h-44",
    "max-h-48",
    "max-h-52",
    "max-h-56",
    "max-h-60",
    "max-h-64",
    "max-h-72",
    "max-h-80",
    "max-h-96",
    "max-h-px",
    "max-h-0.5",
    "max-h-1.5",
    "max-h-2.5",
    "max-h-3.5",
    "max-h-none",
    "max-h-full",
    "max-h-screen",
    "max-h-min",
    "max-h-max",
    "max-h-fit",
  ],
  minWidths: [
    "min-w-0",
    "min-w-full",
    "min-w-min",
    "min-w-max",
    "min-w-fit",
  ],
  minHeights: [
    "min-h-0",
    "min-h-full",
    "min-h-screen",
    "min-h-min",
    "min-h-max",
    "min-h-fit",
  ],
  marginTop: [
    "mt-0",
    "mt-1",
    "mt-2",
    "mt-3",
    "mt-4",
    "mt-5",
    "mt-6",
    "mt-7",
    "mt-8",
    "mt-9",
    "mt-10",
    "mt-11",
    "mt-12",
    "mt-14",
    "mt-16",
    "mt-20",
    "mt-24",
    "mt-28",
    "mt-32",
    "mt-36",
    "mt-40",
    "mt-44",
    "mt-48",
    "mt-52",
    "mt-56",
    "mt-60",
    "mt-64",
    "mt-72",
    "mt-80",
    "mt-96",
    "mt-px",
    "mt-0.5",
    "mt-1.5",
    "mt-2.5",
    "mt-3.5",
    "-mt-1",
    "-mt-2",
    "-mt-3",
    "-mt-4",
    "-mt-5",
    "-mt-6",
    "-mt-7",
    "-mt-8",
    "-mt-9",
    "-mt-10",
    "-mt-11",
    "-mt-12",
    "-mt-14",
    "-mt-16",
    "-mt-20",
    "-mt-24",
    "-mt-28",
    "-mt-32",
    "-mt-36",
    "-mt-40",
    "-mt-44",
    "-mt-48",
    "-mt-52",
    "-mt-56",
    "-mt-60",
    "-mt-64",
    "-mt-72",
    "-mt-80",
    "-mt-96",
    "-mt-0.5",
    "-mt-1.5",
    "-mt-2.5",
    "-mt-3.5",
  ],
  opacity: [
    "opacity-0",
    "opacity-5",
    "opacity-10",
    "opacity-15",
    "opacity-20",
    "opacity-25",
    "opacity-30",
    "opacity-35",
    "opacity-40",
    "opacity-45",
    "opacity-50",
    "opacity-55",
    "opacity-60",
    "opacity-65",
    "opacity-70",
    "opacity-75",
    "opacity-80",
    "opacity-85",
    "opacity-90",
    "opacity-95",
    "opacity-100",
  ],
  display: [
    "hidden",
    "block",
    "inline-block",
    "inline",
    "flex",
    "inline-flex",
    "table",
    "inline-table",
    "table-caption",
    "table-cell",
    "table-column",
    "table-column-group",
    "table-footer-group",
    "table-header-group",
    "table-row-group",
    "table-row",
    "flow-root",
    "grid",
    "inline-grid",
    "contents",
    "list-item",
  ],
  position: [
    "static",
    "fixed",
    "absolute",
    "relative",
    "sticky",
  ],
  overflow: [
    "overflow-auto",
    "overflow-hidden",
    "overflow-clip",
    "overflow-visible",
    "overflow-scroll",
    "overflow-x-auto",
    "overflow-y-auto",
    "overflow-x-hidden",
    "overflow-y-hidden",
    "overflow-x-clip",
    "overflow-y-clip",
    "overflow-x-visible",
    "overflow-y-visible",
    "overflow-x-scroll",
    "overflow-y-scroll",
  ],
  flexDirection: [
    "flex-row",
    "flex-row-reverse",
    "flex-col",
    "flex-col-reverse",
  ],
  flexBase: [
    "flex-1",
    "flex-auto",
    "flex-initial",
    "flex-none",
  ],
  helpers: ["flex", "grid"],
  wrap: ["flex-wrap", "flex-wrap-reverse", "flex-nowrap"],
  grow: ["grow", "grow-0"],
  shrink: ["shrink", "shrink-0"],
  alignItems: [
    "items-start",
    "items-end",
    "items-center",
    "items-baseline",
    "items-stretch",
  ],
  justifyContent: [
    "justify-start",
    "justify-end",
    "justify-center",
    "justify-between",
    "justify-around",
    "justify-evenly",
  ],
  alignSelf: [
    "self-auto",
    "self-start",
    "self-end",
    "self-center",
    "self-stretch",
    "self-baseline",
  ],
  justifySelf: [
    "justify-self-auto",
    "justify-self-start",
    "justify-self-end",
    "justify-self-center",
    "justify-self-stretch",
  ],
  justifyItems: [
    "justify-items-start",
    "justify-items-end",
    "justify-items-center",
    "justify-items-stretch",
  ],
  gridCols: [
    "grid-cols-1",
    "grid-cols-2",
    "grid-cols-3",
    "grid-cols-4",
    "grid-cols-5",
    "grid-cols-6",
    "grid-cols-7",
    "grid-cols-8",
    "grid-cols-9",
    "grid-cols-10",
    "grid-cols-11",
    "grid-cols-12",
    "grid-cols-none",
    "grid-cols-subgrid",
  ],
  gridRows: [
    "grid-rows-1",
    "grid-rows-2",
    "grid-rows-3",
    "grid-rows-4",
    "grid-rows-5",
    "grid-rows-6",
    "grid-rows-7",
    "grid-rows-8",
    "grid-rows-9",
    "grid-rows-10",
    "grid-rows-11",
    "grid-rows-12",
    "grid-rows-none",
    "grid-rows-subgrid",
  ],
  gridAutoFlow: [
    "grid-flow-row",
    "grid-flow-col",
    "grid-flow-row-dense",
    "grid-flow-col-dense",
  ],
  gridAutoColumns: [
    "auto-cols-auto",
    "auto-cols-min",
    "auto-cols-max",
    "auto-cols-fr",
  ],
  gridAutoRows: [
    "auto-rows-auto",
    "auto-rows-min",
    "auto-rows-max",
    "auto-rows-fr",
  ],
  gridColSpan: [
    "col-span-1",
    "col-span-2",
    "col-span-3",
    "col-span-4",
    "col-span-5",
    "col-span-6",
    "col-span-7",
    "col-span-8",
    "col-span-9",
    "col-span-10",
    "col-span-11",
    "col-span-12",
    "col-auto",
    "col-span-full",
  ],
  gridColStart: [
    "col-start-1",
    "col-start-2",
    "col-start-3",
    "col-start-4",
    "col-start-5",
    "col-start-6",
    "col-start-7",
    "col-start-8",
    "col-start-9",
    "col-start-10",
    "col-start-11",
    "col-start-12",
    "col-start-13",
    "col-start-auto",
  ],
  gridColEnd: [
    "col-end-1",
    "col-end-2",
    "col-end-3",
    "col-end-4",
    "col-end-5",
    "col-end-6",
    "col-end-7",
    "col-end-8",
    "col-end-9",
    "col-end-10",
    "col-end-11",
    "col-end-12",
    "col-end-13",
    "col-end-auto",
  ],
  gridRowSpan: [
    "row-auto",
    "row-span-1",
    "row-span-2",
    "row-span-3",
    "row-span-4",
    "row-span-5",
    "row-span-6",
    "row-span-full",
  ],
  gridRowStart: [
    "row-start-1",
    "row-start-2",
    "row-start-3",
    "row-start-4",
    "row-start-5",
    "row-start-6",
    "row-start-7",
    "row-start-8",
    "row-start-9",
    "row-start-10",
    "row-start-11",
    "row-start-12",
    "row-start-13",
    "row-start-auto",
  ],
  gridRowEnd: [
    "row-end-1",
    "row-end-2",
    "row-end-3",
    "row-end-4",
    "row-end-5",
    "row-end-6",
    "row-end-7",
    "row-end-8",
    "row-end-9",
    "row-end-10",
    "row-end-11",
    "row-end-12",
    "row-end-13",
    "row-end-auto",
  ],
  placeContent: [
    "place-content-center",
    "place-content-start",
    "place-content-end",
    "place-content-between",
    "place-content-around",
    "place-content-evenly",
    "place-content-stretch",
  ],
  placeItems: [
    "place-items-start",
    "place-items-end",
    "place-items-center",
    "place-items-stretch",
  ],
  placeSelf: [
    "place-self-auto",
    "place-self-start",
    "place-self-end",
    "place-self-center",
    "place-self-stretch",
  ],
  inset: [
    "inset-0",
    "inset-1",
    "inset-2",
    "inset-3",
    "inset-4",
    "inset-5",
    "inset-6",
    "inset-7",
    "inset-8",
    "inset-9",
    "inset-10",
    "inset-11",
    "inset-12",
    "inset-14",
    "inset-16",
    "inset-20",
    "inset-24",
    "inset-28",
    "inset-32",
    "inset-36",
    "inset-40",
    "inset-44",
    "inset-48",
    "inset-52",
    "inset-56",
    "inset-60",
    "inset-64",
    "inset-72",
    "inset-80",
    "inset-96",
    "inset-px",
    "inset-0.5",
    "inset-1.5",
    "inset-2.5",
    "inset-3.5",
    "inset-auto",
    "inset-1/2",
    "inset-1/3",
    "inset-2/3",
    "inset-1/4",
    "inset-2/4",
    "inset-3/4",
    "inset-full",
    "inset-x-0",
    "inset-x-1",
    "inset-x-2",
    "inset-x-3",
    "inset-x-4",
    "inset-x-5",
    "inset-x-6",
    "inset-x-7",
    "inset-x-8",
    "inset-x-9",
    "inset-x-10",
    "inset-x-11",
    "inset-x-12",
    "inset-x-14",
    "inset-x-16",
    "inset-x-20",
    "inset-x-24",
    "inset-x-28",
    "inset-x-32",
    "inset-x-36",
    "inset-x-40",
    "inset-x-44",
    "inset-x-48",
    "inset-x-52",
    "inset-x-56",
    "inset-x-60",
    "inset-x-64",
    "inset-x-72",
    "inset-x-80",
    "inset-x-96",
    "inset-x-px",
    "inset-x-0.5",
    "inset-x-1.5",
    "inset-x-2.5",
    "inset-x-3.5",
    "inset-x-auto",
    "inset-x-1/2",
    "inset-x-1/3",
    "inset-x-2/3",
    "inset-x-1/4",
    "inset-x-2/4",
    "inset-x-3/4",
    "inset-x-full",
    "inset-y-0",
    "inset-y-1",
    "inset-y-2",
    "inset-y-3",
    "inset-y-4",
    "inset-y-5",
    "inset-y-6",
    "inset-y-7",
    "inset-y-8",
    "inset-y-9",
    "inset-y-10",
    "inset-y-11",
    "inset-y-12",
    "inset-y-14",
    "inset-y-16",
    "inset-y-20",
    "inset-y-24",
    "inset-y-28",
    "inset-y-32",
    "inset-y-36",
    "inset-y-40",
    "inset-y-44",
    "inset-y-48",
    "inset-y-52",
    "inset-y-56",
    "inset-y-60",
    "inset-y-64",
    "inset-y-72",
    "inset-y-80",
    "inset-y-96",
    "inset-y-px",
    "inset-y-0.5",
    "inset-y-1.5",
    "inset-y-2.5",
    "inset-y-3.5",
    "inset-y-auto",
    "inset-y-1/2",
    "inset-y-1/3",
    "inset-y-2/3",
    "inset-y-1/4",
    "inset-y-2/4",
    "inset-y-3/4",
    "inset-y-full",
  ],
  top: [
    "top-0",
    "top-1",
    "top-2",
    "top-3",
    "top-4",
    "top-5",
    "top-6",
    "top-7",
    "top-8",
    "top-9",
    "top-10",
    "top-11",
    "top-12",
    "top-14",
    "top-16",
    "top-20",
    "top-24",
    "top-28",
    "top-32",
    "top-36",
    "top-40",
    "top-44",
    "top-48",
    "top-52",
    "top-56",
    "top-60",
    "top-64",
    "top-72",
    "top-80",
    "top-96",
    "top-px",
    "top-0.5",
    "top-1.5",
    "top-2.5",
    "top-3.5",
    "top-auto",
    "top-1/2",
    "top-1/3",
    "top-2/3",
    "top-1/4",
    "top-2/4",
    "top-3/4",
    "top-full",
  ],
  right: [
    "right-0",
    "right-1",
    "right-2",
    "right-3",
    "right-4",
    "right-5",
    "right-6",
    "right-7",
    "right-8",
    "right-9",
    "right-10",
    "right-11",
    "right-12",
    "right-14",
    "right-16",
    "right-20",
    "right-24",
    "right-28",
    "right-32",
    "right-36",
    "right-40",
    "right-44",
    "right-48",
    "right-52",
    "right-56",
    "right-60",
    "right-64",
    "right-72",
    "right-80",
    "right-96",
    "right-px",
    "right-0.5",
    "right-1.5",
    "right-2.5",
    "right-3.5",
    "right-auto",
    "right-1/2",
    "right-1/3",
    "right-2/3",
    "right-1/4",
    "right-2/4",
    "right-3/4",
    "right-full",
  ],
  bottom: [
    "bottom-0",
    "bottom-1",
    "bottom-2",
    "bottom-3",
    "bottom-4",
    "bottom-5",
    "bottom-6",
    "bottom-7",
    "bottom-8",
    "bottom-9",
    "bottom-10",
    "bottom-11",
    "bottom-12",
    "bottom-14",
    "bottom-16",
    "bottom-20",
    "bottom-24",
    "bottom-28",
    "bottom-32",
    "bottom-36",
    "bottom-40",
    "bottom-44",
    "bottom-48",
    "bottom-52",
    "bottom-56",
    "bottom-60",
    "bottom-64",
    "bottom-72",
    "bottom-80",
    "bottom-96",
    "bottom-px",
    "bottom-0.5",
    "bottom-1.5",
    "bottom-2.5",
    "bottom-3.5",
    "bottom-auto",
    "bottom-1/2",
    "bottom-1/3",
    "bottom-2/3",
    "bottom-1/4",
    "bottom-2/4",
    "bottom-3/4",
    "bottom-full",
  ],
  left: [
    "left-0",
    "left-1",
    "left-2",
    "left-3",
    "left-4",
    "left-5",
    "left-6",
    "left-7",
    "left-8",
    "left-9",
    "left-10",
    "left-11",
    "left-12",
    "left-14",
    "left-16",
    "left-20",
    "left-24",
    "left-28",
    "left-32",
    "left-36",
    "left-40",
    "left-44",
    "left-48",
    "left-52",
    "left-56",
    "left-60",
    "left-64",
    "left-72",
    "left-80",
    "left-96",
    "left-px",
    "left-0.5",
    "left-1.5",
    "left-2.5",
    "left-3.5",
    "left-auto",
    "left-1/2",
    "left-1/3",
    "left-2/3",
    "left-1/4",
    "left-2/4",
    "left-3/4",
    "left-full",
  ],
  zIndex: [
    "z-0",
    "z-10",
    "z-20",
    "z-30",
    "z-40",
    "z-50",
    "z-auto",
  ],
  cursor: [
    "cursor-auto",
    "cursor-default",
    "cursor-pointer",
    "cursor-wait",
    "cursor-text",
    "cursor-move",
    "cursor-help",
    "cursor-not-allowed",
    "cursor-none",
    "cursor-context-menu",
    "cursor-progress",
    "cursor-cell",
    "cursor-crosshair",
    "cursor-vertical-text",
    "cursor-alias",
    "cursor-copy",
    "cursor-no-drop",
    "cursor-grab",
    "cursor-grabbing",
    "cursor-all-scroll",
    "cursor-col-resize",
    "cursor-row-resize",
    "cursor-n-resize",
    "cursor-e-resize",
    "cursor-s-resize",
    "cursor-w-resize",
    "cursor-ne-resize",
    "cursor-nw-resize",
    "cursor-se-resize",
    "cursor-sw-resize",
    "cursor-ew-resize",
    "cursor-ns-resize",
    "cursor-nesw-resize",
    "cursor-nwse-resize",
    "cursor-zoom-in",
    "cursor-zoom-out",
  ],
  order: [
    "order-1",
    "order-2",
    "order-3",
    "order-4",
    "order-5",
    "order-6",
    "order-7",
    "order-8",
    "order-9",
    "order-10",
    "order-11",
    "order-12",
    "order-first",
    "order-last",
    "order-none",
  ],
  objectFit: [
    "object-contain",
    "object-cover",
    "object-fill",
    "object-none",
    "object-scale-down",
  ],
  objectPosition: [
    "object-bottom",
    "object-center",
    "object-left",
    "object-bottom-left",
    "object-top-left",
    "object-right",
    "object-bottom-right",
    "object-top-right",
    "object-top",
  ],
  aspectRatio: ["aspect-auto", "aspect-square", "aspect-video"],
  textDecoration: [
    "underline",
    "overline",
    "line-through",
    "no-underline",
  ],
  decorationStyle: [
    "decoration-solid",
    "decoration-double",
    "decoration-dotted",
    "decoration-dashed",
    "decoration-wavy",
  ],
  decorationThickness: [
    "decoration-auto",
    "decoration-from-font",
    "decoration-0",
    "decoration-1",
    "decoration-2",
    "decoration-4",
    "decoration-8",
  ],
  transform: [
    "uppercase",
    "lowercase",
    "capitalize",
    "normal-case",
  ],
  wordBreak: [
    "break-normal",
    "wrap-break-word",
    "break-all",
    "break-keep",
  ],
  textOverflow: ["truncate", "text-ellipsis", "text-clip"],
  textAlign: [
    "text-left",
    "text-center",
    "text-right",
    "text-justify",
    "text-start",
    "text-end",
  ],
  whiteSpace: [
    "whitespace-normal",
    "whitespace-nowrap",
    "whitespace-pre",
    "whitespace-pre-line",
    "whitespace-pre-wrap",
  ],
  verticalAlign: [
    "align-baseline",
    "align-top",
    "align-middle",
    "align-bottom",
    "align-text-top",
    "align-text-bottom",
    "align-sub",
    "align-super",
  ],
  fontSmoothing: ["antialiased", "subpixel-antialiased"],
  fontStyle: ["italic", "not-italic"],
  float: ["float-right", "float-left", "float-none"],
  indent: [
    "indent-0",
    "indent-1",
    "indent-2",
    "indent-3",
    "indent-4",
    "indent-5",
    "indent-6",
    "indent-7",
    "indent-8",
    "indent-9",
    "indent-10",
    "indent-11",
    "indent-12",
    "indent-14",
    "indent-16",
    "indent-20",
    "indent-24",
    "indent-28",
    "indent-32",
    "indent-36",
    "indent-40",
    "indent-44",
    "indent-48",
    "indent-52",
    "indent-56",
    "indent-60",
    "indent-64",
    "indent-72",
    "indent-80",
    "indent-96",
    "indent-px",
    "indent-0.5",
    "indent-1.5",
    "indent-2.5",
    "indent-3.5",
  ],
  transitionProperty: [
    "transition-none",
    "transition-all",
    "transition",
    "transition-colors",
    "transition-opacity",
    "transition-shadow",
    "transition-transform",
  ],
  duration: [
    "duration-0",
    "duration-75",
    "duration-100",
    "duration-150",
    "duration-200",
    "duration-300",
    "duration-500",
    "duration-700",
    "duration-1000",
    "duration",
  ],
  delay: [
    "delay-0",
    "delay-75",
    "delay-100",
    "delay-150",
    "delay-200",
    "delay-300",
    "delay-500",
    "delay-700",
    "delay-1000",
  ],
  ease: [
    "ease",
    "ease-linear",
    "ease-in",
    "ease-out",
    "ease-in-out",
  ],
  twAnimate: [
    "animate-none",
    "animate-spin",
    "animate-ping",
    "animate-pulse",
    "animate-bounce",
  ],
  scale: [
    "scale-0",
    "scale-50",
    "scale-75",
    "scale-90",
    "scale-95",
    "scale-100",
    "scale-105",
    "scale-110",
    "scale-125",
    "scale-150",
  ],
  scaleX: [
    "scale-x-0",
    "scale-x-50",
    "scale-x-75",
    "scale-x-90",
    "scale-x-95",
    "scale-x-100",
    "scale-x-105",
    "scale-x-110",
    "scale-x-125",
    "scale-x-150",
  ],
  scaleY: [
    "scale-y-0",
    "scale-y-50",
    "scale-y-75",
    "scale-y-90",
    "scale-y-95",
    "scale-y-100",
    "scale-y-105",
    "scale-y-110",
    "scale-y-125",
    "scale-y-150",
  ],
  rotate: [
    "rotate-0",
    "rotate-1",
    "rotate-2",
    "rotate-3",
    "rotate-6",
    "rotate-12",
    "rotate-45",
    "rotate-90",
    "rotate-180",
    "-rotate-1",
    "-rotate-2",
    "-rotate-3",
    "-rotate-6",
    "-rotate-12",
    "-rotate-45",
    "-rotate-90",
    "-rotate-180",
  ],
  skewX: [
    "skew-x-0",
    "skew-x-1",
    "skew-x-2",
    "skew-x-3",
    "skew-x-6",
    "skew-x-12",
  ],
  skewY: [
    "skew-y-0",
    "skew-y-1",
    "skew-y-2",
    "skew-y-3",
    "skew-y-6",
    "skew-y-12",
  ],
  transformOrigin: [
    "origin-center",
    "origin-top",
    "origin-top-right",
    "origin-right",
    "origin-bottom-right",
    "origin-bottom",
    "origin-bottom-left",
    "origin-left",
    "origin-top-left",
  ],
  translateX: [
    "translate-x-0",
    "translate-x-1",
    "translate-x-2",
    "translate-x-3",
    "translate-x-4",
    "translate-x-5",
    "translate-x-6",
    "translate-x-7",
    "translate-x-8",
    "translate-x-9",
    "translate-x-10",
    "translate-x-11",
    "translate-x-12",
    "translate-x-14",
    "translate-x-16",
    "translate-x-20",
    "translate-x-24",
    "translate-x-28",
    "translate-x-32",
    "translate-x-36",
    "translate-x-40",
    "translate-x-44",
    "translate-x-48",
    "translate-x-52",
    "translate-x-56",
    "translate-x-60",
    "translate-x-64",
    "translate-x-72",
    "translate-x-80",
    "translate-x-96",
    "translate-x-px",
    "translate-x-0.5",
    "translate-x-1.5",
    "translate-x-2.5",
    "translate-x-3.5",
    "translate-x-auto",
    "translate-x-1/2",
    "translate-x-1/3",
    "translate-x-2/3",
    "translate-x-1/4",
    "translate-x-2/4",
    "translate-x-3/4",
    "translate-x-full",
  ],
  translateY: [
    "translate-y-0",
    "translate-y-1",
    "translate-y-2",
    "translate-y-3",
    "translate-y-4",
    "translate-y-5",
    "translate-y-6",
    "translate-y-7",
    "translate-y-8",
    "translate-y-9",
    "translate-y-10",
    "translate-y-11",
    "translate-y-12",
    "translate-y-14",
    "translate-y-16",
    "translate-y-20",
    "translate-y-24",
    "translate-y-28",
    "translate-y-32",
    "translate-y-36",
    "translate-y-40",
    "translate-y-44",
    "translate-y-48",
    "translate-y-52",
    "translate-y-56",
    "translate-y-60",
    "translate-y-64",
    "translate-y-72",
    "translate-y-80",
    "translate-y-96",
    "translate-y-px",
    "translate-y-0.5",
    "translate-y-1.5",
    "translate-y-2.5",
    "translate-y-3.5",
    "translate-y-auto",
    "translate-y-1/2",
    "translate-y-1/3",
    "translate-y-2/3",
    "translate-y-1/4",
    "translate-y-2/4",
    "translate-y-3/4",
    "translate-y-full",
  ],
  twTransform: ["transform", "transform-cpu", "transform-gpu"],
  blur: [
    "blur-0",
    "blur-none",
    "blur-sm",
    "blur",
    "blur-md",
    "blur-lg",
    "blur-xl",
    "blur-2xl",
    "blur-3xl",
  ],
  backdropBlur: [
    "backdrop-blur-0",
    "backdrop-blur-none",
    "backdrop-blur-sm",
    "backdrop-blur",
    "backdrop-blur-md",
    "backdrop-blur-lg",
    "backdrop-blur-xl",
    "backdrop-blur-2xl",
    "backdrop-blur-3xl",
  ],
  brightness: [
    "brightness-0",
    "brightness-50",
    "brightness-75",
    "brightness-90",
    "brightness-95",
    "brightness-100",
    "brightness-105",
    "brightness-110",
    "brightness-125",
    "brightness-150",
    "brightness-200",
  ],
  backdropBrightness: [
    "backdrop-brightness-0",
    "backdrop-brightness-50",
    "backdrop-brightness-75",
    "backdrop-brightness-90",
    "backdrop-brightness-95",
    "backdrop-brightness-100",
    "backdrop-brightness-105",
    "backdrop-brightness-110",
    "backdrop-brightness-125",
    "backdrop-brightness-150",
    "backdrop-brightness-200",
  ],
  contrast: [
    "contrast-0",
    "contrast-50",
    "contrast-75",
    "contrast-100",
    "contrast-125",
    "contrast-150",
    "contrast-200",
  ],
  backdropContrast: [
    "backdrop-contrast-0",
    "backdrop-contrast-50",
    "backdrop-contrast-75",
    "backdrop-contrast-100",
    "backdrop-contrast-125",
    "backdrop-contrast-150",
    "backdrop-contrast-200",
  ],
  grayscale: ["grayscale-0", "grayscale"],
  backdropGrayscale: ["backdrop-grayscale-0", "backdrop-grayscale"],
  hueRotate: [
    "hue-rotate-0",
    "hue-rotate-15",
    "hue-rotate-30",
    "hue-rotate-60",
    "hue-rotate-90",
    "hue-rotate-180",
  ],
  backdropHueRotate: [
    "backdrop-hue-rotate-0",
    "backdrop-hue-rotate-15",
    "backdrop-hue-rotate-30",
    "backdrop-hue-rotate-60",
    "backdrop-hue-rotate-90",
    "backdrop-hue-rotate-180",
  ],
  invert: ["invert-0", "invert"],
  backdropInvert: ["backdrop-invert-0", "backdrop-invert"],
  saturate: [
    "saturate-0",
    "saturate-50",
    "saturate-100",
    "saturate-150",
    "saturate-200",
  ],
  backdropSaturate: [
    "backdrop-saturate-0",
    "backdrop-saturate-50",
    "backdrop-saturate-100",
    "backdrop-saturate-150",
    "backdrop-saturate-200",
  ],
  sepia: ["sepia-0", "sepia"],
  backdropSepia: ["backdrop-sepia-0", "backdrop-sepia"],
  backdropOpacity: [
    "backdrop-opacity-0",
    "backdrop-opacity-5",
    "backdrop-opacity-10",
    "backdrop-opacity-15",
    "backdrop-opacity-20",
    "backdrop-opacity-25",
    "backdrop-opacity-30",
    "backdrop-opacity-35",
    "backdrop-opacity-40",
    "backdrop-opacity-45",
    "backdrop-opacity-50",
    "backdrop-opacity-55",
    "backdrop-opacity-60",
    "backdrop-opacity-65",
    "backdrop-opacity-70",
    "backdrop-opacity-75",
    "backdrop-opacity-80",
    "backdrop-opacity-85",
    "backdrop-opacity-90",
    "backdrop-opacity-95",
    "backdrop-opacity-100",
  ],
  willChange: [
    "will-change-auto",
    "will-change-scroll",
    "will-change-contents",
    "will-change-transform",
  ],

  // ─── Gap axis variants ─────────────────────────────────────────────────────
  gapX: [
    "gap-x-0", "gap-x-0.5", "gap-x-1", "gap-x-1.5", "gap-x-2", "gap-x-2.5",
    "gap-x-3", "gap-x-3.5", "gap-x-4", "gap-x-5", "gap-x-6", "gap-x-7",
    "gap-x-8", "gap-x-9", "gap-x-10", "gap-x-11", "gap-x-12", "gap-x-14",
    "gap-x-16", "gap-x-20", "gap-x-24", "gap-x-28", "gap-x-32", "gap-x-36",
    "gap-x-40", "gap-x-44", "gap-x-48", "gap-x-52", "gap-x-56", "gap-x-60",
    "gap-x-64", "gap-x-72", "gap-x-80", "gap-x-96",
  ],
  gapY: [
    "gap-y-0", "gap-y-0.5", "gap-y-1", "gap-y-1.5", "gap-y-2", "gap-y-2.5",
    "gap-y-3", "gap-y-3.5", "gap-y-4", "gap-y-5", "gap-y-6", "gap-y-7",
    "gap-y-8", "gap-y-9", "gap-y-10", "gap-y-11", "gap-y-12", "gap-y-14",
    "gap-y-16", "gap-y-20", "gap-y-24", "gap-y-28", "gap-y-32", "gap-y-36",
    "gap-y-40", "gap-y-44", "gap-y-48", "gap-y-52", "gap-y-56", "gap-y-60",
    "gap-y-64", "gap-y-72", "gap-y-80", "gap-y-96",
  ],

  // ─── Visibility & interactivity ────────────────────────────────────────────
  visibility: ["visible", "invisible", "collapse"],
  pointerEvents: ["pointer-events-none", "pointer-events-auto"],
  userSelect: ["select-none", "select-text", "select-all", "select-auto"],
  resize: ["resize-none", "resize", "resize-y", "resize-x"],
  touchAction: [
    "touch-auto", "touch-none", "touch-pan-x", "touch-pan-left",
    "touch-pan-right", "touch-pan-y", "touch-pan-up", "touch-pan-down",
    "touch-pinch-zoom", "touch-manipulation",
  ],
  scrollBehavior: ["scroll-auto", "scroll-smooth"],
  scrollSnapAlign: ["snap-start", "snap-end", "snap-center", "snap-align-none"],
  scrollSnapStop: ["snap-normal", "snap-always"],
  scrollSnapType: ["snap-none", "snap-x", "snap-y", "snap-both", "snap-mandatory", "snap-proximity"],
  appearance: ["appearance-none", "appearance-auto"],

  // ─── Background extras ─────────────────────────────────────────────────────
  bgClip: ["bg-clip-border", "bg-clip-padding", "bg-clip-content", "bg-clip-text"],
  bgBlend: [
    "bg-blend-normal", "bg-blend-multiply", "bg-blend-screen", "bg-blend-overlay",
    "bg-blend-darken", "bg-blend-lighten", "bg-blend-color-dodge", "bg-blend-color-burn",
    "bg-blend-hard-light", "bg-blend-soft-light", "bg-blend-difference",
    "bg-blend-exclusion", "bg-blend-hue", "bg-blend-saturation", "bg-blend-color",
    "bg-blend-luminosity",
  ],
  mixBlend: [
    "mix-blend-normal", "mix-blend-multiply", "mix-blend-screen", "mix-blend-overlay",
    "mix-blend-darken", "mix-blend-lighten", "mix-blend-color-dodge", "mix-blend-color-burn",
    "mix-blend-hard-light", "mix-blend-soft-light", "mix-blend-difference",
    "mix-blend-exclusion", "mix-blend-hue", "mix-blend-saturation", "mix-blend-color",
    "mix-blend-luminosity", "mix-blend-plus-lighter",
  ],

  // ─── Divide ────────────────────────────────────────────────────────────────
  divideX: ["divide-x-0", "divide-x", "divide-x-2", "divide-x-4", "divide-x-8", "divide-x-reverse"],
  divideY: ["divide-y-0", "divide-y", "divide-y-2", "divide-y-4", "divide-y-8", "divide-y-reverse"],
  divideStyle: ["divide-solid", "divide-dashed", "divide-dotted", "divide-double", "divide-none"],

  // ─── Outline style ─────────────────────────────────────────────────────────
  outlineStyle: ["outline-none", "outline", "outline-dashed", "outline-dotted", "outline-double"],

  // ─── Layout extras ─────────────────────────────────────────────────────────
  boxSizing: ["box-border", "box-content"],
  isolation: ["isolate", "isolation-auto"],
  columns: [
    "columns-1", "columns-2", "columns-3", "columns-4", "columns-5", "columns-6",
    "columns-7", "columns-8", "columns-9", "columns-10", "columns-11", "columns-12",
    "columns-auto", "columns-3xs", "columns-2xs", "columns-xs", "columns-sm",
    "columns-md", "columns-lg", "columns-xl", "columns-2xl", "columns-3xl",
    "columns-4xl", "columns-5xl", "columns-6xl", "columns-7xl",
  ],
  breakBefore: ["break-before-auto", "break-before-avoid", "break-before-all", "break-before-avoid-page", "break-before-page", "break-before-left", "break-before-right", "break-before-column"],
  breakInside: ["break-inside-auto", "break-inside-avoid", "break-inside-avoid-page", "break-inside-avoid-column"],
  breakAfter: ["break-after-auto", "break-after-avoid", "break-after-all", "break-after-avoid-page", "break-after-page", "break-after-left", "break-after-right", "break-after-column"],

  // ─── List & table ──────────────────────────────────────────────────────────
  listStyleType: ["list-none", "list-disc", "list-decimal"],
  listStylePosition: ["list-inside", "list-outside"],
  tableLayout: ["table-auto", "table-fixed"],
  captionSide: ["caption-top", "caption-bottom"],

  // ─── SVG ───────────────────────────────────────────────────────────────────
  fill: ["fill-none", "fill-inherit", "fill-current", "fill-transparent"],
  strokeWidth: ["stroke-0", "stroke-1", "stroke-2"],
  stroke: ["stroke-none", "stroke-inherit", "stroke-current", "stroke-transparent"],

  // ─── Accessibility ─────────────────────────────────────────────────────────
  srOnly: ["sr-only", "not-sr-only"],

  // ─── Content ───────────────────────────────────────────────────────────────
  content: ["content-none"],

  // ─── Text wrap / hyphens ───────────────────────────────────────────────────
  textWrap: ["text-wrap", "text-nowrap", "text-balance", "text-pretty"],
  hyphens: ["hyphens-none", "hyphens-manual", "hyphens-auto"],

  fonts,
};

// ─── AllStyles (computed at module load from TailwindStyles + custom colors) ──

const _allSet = new Set<string>();
for (const key of Object.keys(TailwindStyles)) {
  const arr = TailwindStyles[key];
  if (Array.isArray(arr)) for (const cls of arr) if (cls) _allSet.add(cls);
}
// Custom PageHub color variants
for (const color of ["primary", "secondary", "accent"]) {
  for (const shade of ["50","100","200","300","400","500","600","700","800","900","950","DEFAULT"]) {
    const suffix = shade === "DEFAULT" ? "" : `-${shade}`;
    _allSet.add(`bg-${color}${suffix}`);
    _allSet.add(`text-${color}${suffix}`);
    _allSet.add(`border-${color}${suffix}`);
  }
}
export const AllStylesSet = _allSet;
export const AllStyles: string[] = [..._allSet];

// ─── Prefix → prop key mapping (for arbitrary value support) ───────────────

export const PREFIX_TO_KEY: Record<string, string> = {
  "pointer-events-": "pointerEvents",
  "touch-manipulation": "touchAction",
  "touch-pinch-zoom": "touchAction",
  "break-before-": "breakBefore",
  "break-inside-": "breakInside",
  "break-after-": "breakAfter",
  "divide-solid": "divideStyle",
  "divide-dashed": "divideStyle",
  "divide-dotted": "divideStyle",
  "divide-double": "divideStyle",
  "divide-none": "divideStyle",
  "bg-clip-": "bgClip",
  "bg-blend-": "bgBlend",
  "mix-blend-": "mixBlend",
  "scroll-snap-": "scrollSnapType",
  "snap-start": "scrollSnapAlign",
  "snap-end": "scrollSnapAlign",
  "snap-center": "scrollSnapAlign",
  "snap-always": "scrollSnapStop",
  "snap-normal": "scrollSnapStop",
  "stroke-width-": "strokeWidth",
  "columns-": "columns",
  "divide-x": "divideX",
  "divide-y": "divideY",
  "select-": "userSelect",
  "resize-": "resize",
  "touch-": "touchAction",
  "scroll-": "scrollBehavior",
  "snap-": "scrollSnapType",
  "fill-": "fill",
  "stroke-": "stroke",
  "gap-x-": "gapX",
  "gap-y-": "gapY",
  "list-": "listStyleType",
  "backdrop-hue-rotate-": "backdropHueRotate",
  "backdrop-brightness-": "backdropBrightness",
  "backdrop-grayscale-": "backdropGrayscale",
  "backdrop-contrast-": "backdropContrast",
  "backdrop-saturate-": "backdropSaturate",
  "backdrop-opacity-": "backdropOpacity",
  "backdrop-invert-": "backdropInvert",
  "backdrop-sepia-": "backdropSepia",
  "backdrop-blur-": "backdropBlur",
  "translate-x-": "translateX",
  "translate-y-": "translateY",
  "will-change-": "willChange",
  "drop-shadow-": "dropShadows",
  "hue-rotate-": "hueRotate",
  "transition-": "transitionProperty",
  "brightness-": "brightness",
  "grid-cols-": "gridCols",
  "grid-rows-": "gridRows",
  "col-start-": "gridColStart",
  "row-start-": "gridRowStart",
  "transform-": "twTransform",
  "grayscale-": "grayscale",
  "col-span-": "gridColSpan",
  "row-span-": "gridRowSpan",
  "tracking-": "tracking",
  "overflow-": "overflow",
  "duration-": "duration",
  "contrast-": "contrast",
  "saturate-": "saturate",
  "scale-x-": "scaleX",
  "scale-y-": "scaleY",
  "col-end-": "gridColEnd",
  "row-end-": "gridRowEnd",
  "rounded-": "radius",
  "leading-": "lineHeight",
  "opacity-": "opacity",
  "animate-": "twAnimate",
  "font-(--": "fontFamily",
  "skew-x-": "skewX",
  "skew-y-": "skewY",
  "object-": "objectFit",
  "aspect-": "aspectRatio",
  "border-": "border",
  "shadow-": "shadow",
  "cursor-": "cursor",
  "invert-": "invert",
  "rotate-": "rotate",
  "origin-": "transformOrigin",
  "bottom-": "bottom",
  "indent-": "indent",
  "max-w-": "maxWidth",
  "max-h-": "maxHeight",
  "min-w-": "minWidth",
  "min-h-": "minHeight",
  "inset-": "inset",
  "delay-": "delay",
  "sepia-": "sepia",
  "scale-": "scale",
  "right-": "right",
  "order-": "order",
  "blur-": "blur",
  "ease-": "ease",
  "font-": "fontWeight",
  "text-": "fontSize",
  "left-": "left",
  "from-": "backgroundGradientFrom",
  "top-": "top",
  "gap-": "gap",
  "via-": "backgroundGradientVia",
  "bg-": "background",
  "mx-": "mx",
  "my-": "my",
  "px-": "px",
  "py-": "py",
  "ml-": "ml",
  "mr-": "mr",
  "mt-": "mt",
  "mb-": "mb",
  "pl-": "pl",
  "pr-": "pr",
  "pt-": "pt",
  "pb-": "pb",
  "to-": "backgroundGradientTo",
  "z-": "zIndex",
  "w-": "width",
  "h-": "height",
  "p-": "p",
  "m-": "m",
};

// Sorted longest-prefix-first for correct matching
export const PREFIX_ENTRIES: [string, string][] = Object.entries(PREFIX_TO_KEY)
  .sort((a, b) => b[0].length - a[0].length);

// ─── Validation ────────────────────────────────────────────────────────────

/** Check if a class is a valid Tailwind utility (known or arbitrary value) */
export function isValidTailwindClass(cls: string): boolean {
  if (AllStylesSet.has(cls)) return true;
  // Arbitrary values: gap-[32px], bg-[#ff0000], w-[calc(100%-2rem)]
  if (/[.+]/.test(cls)) return true;
  // CSS var token syntax: bg-primary, text-(--foreground)
  if (/(.+--.+)/.test(cls)) return true;
  return false;
}

// ─── classNameToVar ────────────────────────────────────────────────────────

/** Stems after `text-` that are font-size utilities, not text colors. */
const CLASSNAME_TO_VAR_TEXT_SIZE_STEM =
  /^(xs|sm|base|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl|8xl|9xl)$/;

/**
 * Map a Tailwind class to its prop key.
 * Uses reverse index for known classes, falls back to prefix matching for arbitrary values.
 * Aligns with toolbar / className-first keys: `TailwindStyles` stores text colors under `text` but UI uses `color`.
 */
export const classNameToVar = (name: string): string | undefined => {
  for (const key of Object.keys(TailwindStyles)) {
    if (RootClassGenProps.includes(key)) continue;
    if (Array.isArray(TailwindStyles[key]) && TailwindStyles[key].includes(name)) {
      if (key === "text") return "color";
      return key;
    }
  }
  const ro = ringOutlineClassKey(name);
  if (ro) return ro;
  if (/^font-\(--[^)]+\)$/.test(name)) return "fontFamily";
  if (name.startsWith("font-[") && name.endsWith("]")) {
    const inner = name.slice(6, -1).trim();
    const q0 = inner.charAt(0);
    if (q0 === "'" || q0 === '"' || q0 === String.fromCharCode(96)) return "fontFamily";
    if (/^family-name\s*:/.test(inner)) return "fontFamily";
    if (/^\d{1,3}$/.test(inner)) return "fontWeight";
    if (/^[A-Za-z0-9_\s-]+$/.test(inner) && /[A-Za-z]/.test(inner)) return "fontFamily";
  }
  for (const [prefix, key] of PREFIX_ENTRIES) {
    if (name.startsWith(prefix)) {
      if (
        key === "fontSize" &&
        name.startsWith("text-") &&
        !CLASSNAME_TO_VAR_TEXT_SIZE_STEM.test(name.slice(5))
      ) {
        return "color";
      }
      return key;
    }
  }
  return undefined;
};
