// ── DaisyUI class → component file mapping ─────────────────────────────────
//
// Load-bearing: the SSR CSS pipeline ships a DaisyUI component file only when a
// page uses one of its class prefixes. Keep entries in sync with the DaisyUI
// component set; this is the entry point for supporting new components on version bumps.

export const DAISYUI_CLASS_MAP: Record<string, string> = {
  alert: "alert.css",
  avatar: "avatar.css",
  badge: "badge.css",
  breadcrumbs: "breadcrumbs.css",
  btn: "button.css",
  card: "card.css",
  carousel: "carousel.css",
  chat: "chat.css",
  checkbox: "checkbox.css",
  collapse: "collapse.css",
  countdown: "countdown.css",
  diff: "diff.css",
  divider: "divider.css",
  dock: "dock.css",
  drawer: "drawer.css",
  dropdown: "dropdown.css",
  fieldset: "fieldset.css",
  "file-input": "fileinput.css",
  filter: "filter.css",
  footer: "footer.css",
  hero: "hero.css",
  indicator: "indicator.css",
  input: "input.css",
  kbd: "kbd.css",
  label: "label.css",
  link: "link.css",
  list: "list.css",
  loading: "loading.css",
  mask: "mask.css",
  menu: "menu.css",
  "mockup-code": "mockup.css",
  "mockup-window": "mockup.css",
  modal: "modal.css",
  navbar: "navbar.css",
  progress: "progress.css",
  "radial-progress": "radialprogress.css",
  radio: "radio.css",
  range: "range.css",
  rating: "rating.css",
  select: "select.css",
  skeleton: "skeleton.css",
  stack: "stack.css",
  stats: "stat.css",
  stat: "stat.css",
  status: "status.css",
  steps: "steps.css",
  step: "steps.css",
  swap: "swap.css",
  tabs: "tab.css",
  tab: "tab.css",
  table: "table.css",
  textarea: "textarea.css",
  timeline: "timeline.css",
  toast: "toast.css",
  toggle: "toggle.css",
  tooltip: "tooltip.css",
};
